---
title: "MC 1: The chaos expansion"
author: "Liam Llamazares--Elias"
date: "2022-05-23"
categories: [Malliavin calculus]
description: "Iterated Itô integrals and their consequences"
bibliography: biblio.bib
format:
  html:
    css: custom_theorems.css
    toc: true
    number-sections: true
    html-math-method: mathjax
    include-in-header:
      text: |
        <script>
        window.MathJax = {
          tex: {
            tags: "ams",
            macros: {
              A: "\\mathbb{A}",
              Aa: "\\mathcal{A}",
              Bb: "\\mathcal{B}",
              C: "\\mathbb{C}",
              Cc: "\\mathcal{C}",
              Dd: "\\mathcal{D}",
              E: "\\mathbb{E}",
              Ee: "\\mathcal{E}",
              F: "\\mathbb{F}",
              Ff: "\\mathcal{F}",
              Gg: "\\mathcal{G}",
              Hh: "\\mathcal{H}",
              II: "\\mathbb{I}",
              Id: "\\bm{I}",
              Ii: "\\mathcal{I}",
              Im: "\\bm{Im}",
              Jj: "\\mathcal{J}",
              K: "\\mathbb{K}",
              KL: ["\\rm{KL}\\left(#1 \\| #2\\right)", 2],
              Kk: "\\mathcal{K}",
              LL: "\\mathbb{L}",
              Ll: "\\mathcal{L}",
              M: "\\mathbb{M}",
              Mm: "\\mathcal{M}",
              N: "\\mathbb{N}",
              Nn: "\\mathcal{N}",
              Oo: "\\mathcal{O}",
              PP: "\\mathbb{P}",
              Pp: "\\mathcal{P}",
              Q: "\\mathbb{Q}",
              Qq: "\\mathcal{Q}",
              R: "\\mathbb{R}",
              Rr: "\\mathcal{R}",
              Ss: "\\mathcal{S}",
              T: "\\mathbb{T}",
              Th: "{\\bm{\\theta}}",
              Thh: "{\\bm{\\Theta}}",
              Tt: "\\mathcal{T}",
              Uu: "\\mathcal{U}",
              Vv: "\\mathcal{V}",
              W: "\\mathbb{W}",
              Ww: "\\mathcal{W}",
              X: "\\mathbb{X}",
              Xx: "\\mathcal{X}",
              Yy: "\\mathcal{Y}",
              Z: "\\mathbb{Z}",
              Zz: "\\mathcal{Z}",
              abs: ["\\left| #1 \\right|", 1],
              alf: "{\\alpha}",
              b: ["{\\bm{#1}}", 1],
              bm: ["\\boldsymbol{#1}", 1],
              br: ["\\left\\langle#1\\right\\rangle", 1],
              bt: "\\beta",
              co: ["\\overset{\\circ}{#1}", 1],
              d: "\\mathrm{d}",
              diag: ["\\operatorname{diag}\\left(#1\\right)", 1],
              dx: "\\,\\mathrm{d}x",
              dy: "\\,\\mathrm{d}y",
              eps: "\\varepsilon",
              et: "{\\bm{\\eta}}",
              ex: ["\\mathrm{exp}\\left(#1\\right)", 1],
              fk: ["\\mathfrak{#1}", 1],
              fracc: ["{#1}/{#2}", 2],
              frc: ["\\left(#2)^{-1}(#1\\right)", 2],
              iso: "\\xrightarrow{\\sim}",
              ker: "\\bm{ker}",
              mat: ["\\begin{bmatrix}{#1}\\end{bmatrix}", 1],
              mathbbm: ["\\mathbb{#1}", 1],
              mathds: ["\\mathbb{#1}", 1],
              norm: ["\\left\\lVert #1 \\right\\rVert", 1],
              om: "\\omega",
              postref: ["\\href{https://nowheredifferentiable.com/posts/#1/}{#3}", 3],
              proj: "\\mathrm{proj}",
              qb: ["\\left[#1\\right]", 1],
              qp: ["\\left(#1\\right)", 1],
              qt: ["\\left(#1\\right)", 1],
              red: ["{\\color{red}#1}", 1],
              rm: ["\\mathrm{#1}", 1],
              set: ["\\left\\{#1\\right\\}", 1],
              star: "*",
              tl: ["\\widetilde{#1}", 1],
              tll: ["\\widetilde{#1}", 1],
              vol: "\\mathrm{vol}",
              wh: ["\\widehat{#1}", 1],
              x: "\\bm{x}",
              xxi: "{\\bm{\\xi}}",
              y: "\\bm{y}"
            }
          }
        };
        </script>
---

This is the first post of many to come on this blog, thanks for joining! This is also the first in a series on Malliavin calculus. This chain is
based on the book [@nunno2008malliavin], and inspired by a reading group on the topic.

## Wiener Itô chaos expansion

### Three line summary

- Square integrable  *deterministic* functions of multiple variables can be repeatedly Itô integrated to get a square-integrable *random* function.
- Repeated integration satisfies an *isometry*.
- Every square-integrable function can be uniquely written as the *sum* of repeated integrals.

### Why this is important

The chaos expansion gives us a way to represent random variables as a sum of functions in $L^2$. This representation can be used to define the Skorokhod integral [@Skorokhodblog].

### Iterated integrals

We will write $\Ff_t$ for the completion of the natural filtration generated by $W(t)$, on some measure space  $\Omega$ and consider an interval $I=[0,T]$ or  $I=[0,+\infty)$. In this second case we say that $T=\infty.$ We also recall the notation

$$
\Mm_t^2:=\{M\in L^2([0,t]\times\Omega)\text{ that are continuous martingales}\}.
$$

We will work with the spaces $L^2(I^n), L^2_S(I^n), L^2(S_n)$ of respectively square-integrable functions, symmetric square-integrable functions, and square-integrable functions on

$$
S_n:=\{0\leq t_1\leq\ldots\leq t_n\leq T\}.
$$

Since these functions don't involve a random variable we call them *deterministic*. Given $f\in L^2(I^n)$ we denote its symmetrization by

$$
f_S:=\frac{1}{n!}\sum_{\sigma} f(t_{\sigma_1},\ldots,t_{\sigma_n}).
$$

Where $\sigma$ is summed over all the permutations of $\{1,\ldots,n\}$.
Note that if $f$ is already symmetric then  $f=f_S$. Given a *deterministic* function we can transform it into a *random* one by taking its Itô integral. By integrating multiple times we obtain the following definition

::: {#def-1}

Let $f\in L^2(S_n)$, then we define the *n-fold Itô integral* as

$$
J_n(f):=\int_I\cdots \int_{0}^{t_3}\int_{0}^{t_2} f(t_1,\ldots,t_n)dW(t_1) dW(t_2)\ldots dW(t_n).
$$

:::

The definition requires some care to make sense of and to make sure it is well defined. For example, note that the variables appearing in the upper bounds of the integration domain are the same as those appearing as integration variables. To better understand the definition, first note that, by the properties of the Itô integral, for each $t_2\leq\cdots\leq t_n$,

$$
F_2(t_2\ldots,t_n):=	\int_{0}^{t_2} f(t_1,\ldots,t_n)dW(t_1) \in \Mm_{t_3}^2.
$$

Where $F_2(\cdot,t_3,\ldots,t_n)\in \Mm_{t_3}^2$ is viewed as a function of $t_2$. Due to the above inclusion $F_2(\cdot,t_3,\ldots,t_n)$ is Itô integrable and

$$
F_3(t_3\ldots,t_n):=	\int_{0}^{t_3} F_2(t_2,\ldots,t_n)dW(t_2) \in \Mm_{t_4}^2  .
$$

Where the above is viewed as a function of $t_3$. Iterating this process we get that $F_n \in \Mm_T^2$ and

$$
J_n(f)=\int_I F_n(t_n)dW(t_n) \in L^2(\Omega).
$$

To notice the subtleties involved, we note that one example of an integral that would be ill-defined however is if for $f\in L^2(I^n)$
we defined

$$
\red{J_n(f)}:=\int_I\cdots \int_I\int_I f(t_1,\ldots,t_n)dW(t_1) dW(t_2)\ldots dW(t_n).
$$

In this case, we have that the first integral is $\Ff_T$ adapted and not $\Ff_{t_2}$ adapted so we cannot continue integrating! As a result, we instead give the following definition for symmetric functions.

::: {#def-2}

Let $f\in L^2_S(I^n)$, then we define

$$
I_n(f):=\int_I\cdots \int_I\int_I f(t_1,\ldots,t_n)dW(t_1) dW(t_2)\ldots dW(t_n):=n! J_n(f).
$$

:::

Where it is important to note that the second equality is by definition and where the rescaling factor is motivated by the fact that, by counting permutations, if $I$ is finite then $\mu(I^n)=n! \mu(S_n)$.

::: {#prp-1 name="Itô's n-th isometry"}

Let $f,g\in L^2(S^n)$ then

$$
\br{J_n(f),J_m(g)}_{L^2(\Omega)}=\br{f,g}_{L^2(S_n)}\delta_{nm}
$$

:::

::: {.proof}

The proof is an application of Itô's (product) isometry to move the expectation into the iterated integrals. If the number of integrals is unequal ($n\neq m$) you get the expectation of an Itô integral which is zero. Otherwise, you just get the (deterministic) inner product.

:::

As a result, we also get by a calculation that if $f,g\in L^2(I^n)$ then

$$
\br{I_n(f),I_m(g)}_{L^2(\Omega)}=n!\br{f_S,g_S}_{L^2(I^n)}\delta_{nm}.
$$

### The chaos expansion

::: {#lem-1 name="Itô's representation theorem"}

Let $\xi\in L^2(\Omega,\Ff_\infty)$, then there exists a unique $X(t)\in \mathbb{L}^2(I)$ such that

$$
\xi=\E[\xi]+\int_{I} X(t)dW(t).
$$

Furthermore it holds that $\norm{X}_{L^2(I\times\Omega)}\leq \norm{\xi}_{L^2(\Omega)}$.

:::

::: {#thm-1 name="Chaos expansion"}

Let $\xi\in L^2(\Omega,\Ff_\infty)$, then there exists a unique sequence of functions $g_n \in L^2(S_n),f_n \in L^2(I^n)$ such that

$$
\xi=\sum_{n=0}^{\infty}  J_n(g_n);\quad \xi=\sum_{n=0}^{\infty} I_n(f_n).
$$

::: {.proof}

The proof is a bit technical but we sketch the main idea which is to iteratively apply Itô's representation theorem to get
\begin{multline*}
\xi=\E[\xi]+\int_I X_1(t)dW(t_1)=\E[\xi]+\int_{I} \E[X_1(t_1)] dW(t_1)\\+ \int_{I}\int_{0}^{t_2} X_2(t_1,t_2) dW(t_1)dW(t_2)= \ldots=\sum_{n=0}^{N}  J_n(g_n)+ \int_{S_{N+1}} X_{N+1} dW^{\otimes(N+1)}.
\end{multline*}
Where $g_0=\E[\xi], g_1(t_1) =\E[X_1](t_1)$ and so on. By an iteration we deduce that if we write $\phi_{N+1}$ for the last integral term, then

$$
\E[\phi_{N+1}^2]\leq\ldots\leq \E[\xi^2].
$$

Furthermore, by Itô's $n$-th isometry we have that the terms in the above sum are orthogonal so

$$
\norm{\xi}_{L^2(\Omega)}=\sum_{n=0}^{N} \norm{J_n(g_n)}_{L^2(\Omega)} +\norm{\phi_{N+1}}_{L^2(\Omega)}.
$$

Since the last term is bounded, we obtain a bound on the $L^2(\Omega)$ norm of the sum uniform in  $n$ so the sum converges. As a result, so does $\phi_N$  to some $\phi_\infty$. It suffices to see that $\phi_\infty=0$. This can be proved using that, by Itô's  $n$-th isometry, $\phi_{N+1}$ is orthogonal to  $J_n(h)$ for any $h\in L^2(\Omega)$ and $n\leq N$. As a result the limit $\phi_\infty$ is orthogonal to $J_n(h)$ for all  $n$  and by a density argument (there are a lot of these functions $J_n(h)$!) we obtain $\phi_\infty=0$. This proves the first sum of the theorem.\\\\
It remains to prove the second part, but this follows by extending the $g_n$ by  $0$ on  $I^n\setminus S_n$ and taking $f_n$ to be the symmetrization of this extension.

:::

:::

## References

::: {#refs}
:::
