project:
  type: website
  output-dir: _site
  resources:
    - _data/recent_comments.json
    - assets/
    - custom_theorems.css
  render:
    - "!posts/Future/**"
    - "*.qmd"
    - "*.md"
    - "posts/**/*.qmd"
    - "posts/**/*.md"

website:
  title: "NoWhere Differentiable Math"
  site-url: index.qmd
  description: "A blog about Mathematics, Spatial statistics, stochastic analysis, and PDEs."
  
  navbar:
    logo: "assets/img/tree.jpg"
    left:
      - text: "HOME PAGE"
        href: index.qmd
      - text: "About"
        href: aboutme.qmd
    right:
      - text: "Posts by Tag"
        href: tags.qmd
      - text: "Resources"
        menu:
          - text: "Terence Tao's blog"
            href: "https://terrytao.wordpress.com/"
          - text: "Lukasz Sliwinski's blog"
            href: "https://lukasz.ls314.com/"
      - text: "Subscribe"
        href: "http://eepurl.com/itcRso"
      - icon: github
        href: https://github.com/LiamLlamazares

  search: true

  page-footer:
    left: "L. Llamazares-Elias"
    right: 
      - icon: github
        href: https://github.com/LiamLlamazares
      - text: "Google Scholar"
        href: "https://scholar.google.com/citations?user=nW7-c62TwJ0C"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    css: custom_theorems.css
    html-math-method: mathjax
    include-in-header:
      text: |
        <script>
        window.MathJax = {
          tex: {
            inlineMath: [['$','$'], ['\\(','\\)']],
            displayMath: [['$$','$$'], ['\\[','\\]']],
            processEscapes: true
          }
        };
        </script>

crossref:
  custom:
    - kind: float
      reference-prefix: Assumption
      key: asm
