---
title: "MC 2: The Skorokhod Integral"
author: "Liam Llamazares--Elias"
date: "2022-05-28"
categories: [Malliavin calculus]
description: "How does one generalize the Itô integral?"
format:
  html:
    css: custom_theorems.css
    toc: true
    number-sections: true
    html-math-method: mathjax
    include-in-header:
      text: |
        <script>
        window.MathJax = {
          tex: {
            tags: "ams",
            macros: {
              A: "\\mathbb{A}",
              Aa: "\\mathcal{A}",
              Bb: "\\mathcal{B}",
              C: "\\mathbb{C}",
              Cc: "\\mathcal{C}",
              Dd: "\\mathcal{D}",
              E: "\\mathbb{E}",
              Ee: "\\mathcal{E}",
              F: "\\mathbb{F}",
              Ff: "\\mathcal{F}",
              Gg: "\\mathcal{G}",
              Hh: "\\mathcal{H}",
              II: "\\mathbb{I}",
              Id: "\\bm{I}",
              Ii: "\\mathcal{I}",
              Im: "\\bm{Im}",
              Jj: "\\mathcal{J}",
              K: "\\mathbb{K}",
              KL: ["\\rm{KL}\\left(#1 \\| #2\\right)", 2],
              Kk: "\\mathcal{K}",
              LL: "\\mathbb{L}",
              Ll: "\\mathcal{L}",
              M: "\\mathbb{M}",
              Mm: "\\mathcal{M}",
              N: "\\mathbb{N}",
              Nn: "\\mathcal{N}",
              Oo: "\\mathcal{O}",
              PP: "\\mathbb{P}",
              Pp: "\\mathcal{P}",
              Q: "\\mathbb{Q}",
              Qq: "\\mathcal{Q}",
              R: "\\mathbb{R}",
              Rr: "\\mathcal{R}",
              Ss: "\\mathcal{S}",
              T: "\\mathbb{T}",
              Th: "{\\bm{\\theta}}",
              Thh: "{\\bm{\\Theta}}",
              Tt: "\\mathcal{T}",
              Uu: "\\mathcal{U}",
              Vv: "\\mathcal{V}",
              W: "\\mathbb{W}",
              Ww: "\\mathcal{W}",
              X: "\\mathbb{X}",
              Xx: "\\mathcal{X}",
              Yy: "\\mathcal{Y}",
              Z: "\\mathbb{Z}",
              Zz: "\\mathcal{Z}",
              abs: ["\\left| #1 \\right|", 1],
              alf: "{\\alpha}",
              b: ["{\\bm{#1}}", 1],
              bm: ["\\boldsymbol{#1}", 1],
              br: ["\\left\\langle#1\\right\\rangle", 1],
              bt: "\\beta",
              co: ["\\overset{\\circ}{#1}", 1],
              d: "\\mathrm{d}",
              diag: ["\\operatorname{diag}\\left(#1\\right)", 1],
              dx: "\\,\\mathrm{d}x",
              dy: "\\,\\mathrm{d}y",
              eps: "\\varepsilon",
              et: "{\\bm{\\eta}}",
              ex: ["\\mathrm{exp}\\left(#1\\right)", 1],
              fk: ["\\mathfrak{#1}", 1],
              fracc: ["{#1}/{#2}", 2],
              frc: ["\\left(#2)^{-1}(#1\\right)", 2],
              iso: "\\xrightarrow{\\sim}",
              ker: "\\bm{ker}",
              mat: ["\\begin{bmatrix}{#1}\\end{bmatrix}", 1],
              mathbbm: ["\\mathbb{#1}", 1],
              mathds: ["\\mathbb{#1}", 1],
              norm: ["\\left\\lVert #1 \\right\\rVert", 1],
              om: "\\omega",
              postref: ["\\href{https://nowheredifferentiable.com/posts/#1/}{#3}", 3],
              proj: "\\mathrm{proj}",
              qb: ["\\left[#1\\right]", 1],
              qp: ["\\left(#1\\right)", 1],
              qt: ["\\left(#1\\right)", 1],
              red: ["{\\color{red}#1}", 1],
              rm: ["\\mathrm{#1}", 1],
              set: ["\\left\\{#1\\right\\}", 1],
              star: "*",
              tl: ["\\widetilde{#1}", 1],
              tll: ["\\widetilde{#1}", 1],
              vol: "\\mathrm{vol}",
              wh: ["\\widehat{#1}", 1],
              x: "\\bm{x}",
              xxi: "{\\bm{\\xi}}",
              y: "\\bm{y}"
            }
          }
        };
        </script>
---

##  Three line summary

- By fixing $t$, one can obtain a chaos expansion for (possibly non-adapted) square integrable stochastic processes $X(t)$.
- The Itô integral of an Itô integrable process $X(t)$ has a chaos expansion.
- This chaos expansion can converge even when $X(t)$ is not adapted to the filtration $\Ff_t$ (and thus not Itô integrable). This allows us to extend the Itô integral to non-adapted processes.

## Why should I care?

If you want to define the Malliavin derivative you need the Skorokhod integral.

## Notation

The same as in [the previous post](../../Malliavin Calculus/1.Chaos_expansion/index.qmd) on the chaos expansion. We will also write $\mathbb{L}^2(I\times \Omega)$ for the space of  [Itô integrable](../../Stochastic Calculus/Ito_integral/index.qmd) functions.

## The chaos expansion of an Itô integral

Our goal in this post is to construct the Skorokhod integral. This serves as a generalization of the Itô integral and the starting point for the definition of the Malliavin derivative. How is this done? Let us first consider a (not-necessarily adapted) stochastic process $X$ such that $X_t\in L^2(\Omega,\Ff_\infty)$ for each $t \in I$. Then we know that by the chaos expansion proved in the previous post, for each $t$ there exists  $f_{n,t}\in L^2(S_n)$ such that

$$
X=\sum_{n=0}^{\infty} I_n(f_{n,t}).
$$

Let us write $f_{n}(\cdot,t):=f_{n,t}$. Note that we are now considering $f_n$ as a function of $n+1$ variables instead of  $n$. In particular, we will be able to consider expressions like  $I_{n+1}(f_n)$ later on. The first thing we do is study what the adaptedness of $X$ means in term of the functions $f_n$ appearing in its chaos expansion.

::: {#lem-1}

Let $X(t) \in L^2(\Omega,\Ff_\infty)$ for each $t \in  I$, then $X$ is adapted iff

$$
f_n(t_1,\ldots,t_n,t)=0,\quad\forall t\leq\max_{i=1,\ldots,n} t_i .
$$

:::

::: {.proof}

Firstly, we note that a stochastic process $X$ is adapted iff $$X_t=\E_{\Ff_t}[X(t)]\quad\forall t\in I.$$ Since the Itô integral is a martingale, we obtain that, by commuting the sum and using the uniqueness of the chaos expansion this is equivalent to requiring that, for all $t$
\begin{multline*}
	I_n(f_n(\cdot,t))\\=	n!\E_{\Ff_t} \left[\int_{I} \left( \int_{0}^{t_n}\cdots \int_{0}^{t_2}f(t_1\ldots t_n,t) dW(t_1) \cdots dW(t_{n-1}) \right)dW(t_n)\right]\\
	=n!\int_{0}^t \int_{0}^{t_n}\cdots \int_{0}^{t_2}f(t_1\ldots t_n,t) dW(t_1) \cdots dW(t_{n-1})dW(t_n)\\= I_n(f_n(\cdot,t) 1_{\max_{t_i\leq t}}),
\end{multline*}
where the commutation of the sum and the integral is justified by the $L^2(\Omega)$ convergence of the chaos expansion ($L^1(\Omega)$ convergence would have been enough).

:::

In particular, we obtain that, since $f_n$ is already symmetric in its first n-coordinates, its symmetrization verifies that

$$
f_{n,S}(t_1,\ldots,t_n,t_{n+1})=\frac{1}{n+1}f_n(t_1,\ldots\hat{t_{j}},\ldots,t_{n+1},t_j),\quad \text{where } j=\text{arg}\max_i t_i.
$$

Using this relationship we can directly calculate the Itô integral of a stochastic process to obtain that.

::: {#thm-1}

Let $X \in \mathbb{L}^2(I\times\Omega)$ then the Itô integral of $X$ is

$$
\int_{I} X(t) dW(t)=\sum_{n=0}^{\infty} I_{n+1}(f_{n,S}).
$$

:::

::: {.proof}

This is a direct calculation using the previous result as

\begin{multline*}
	\int_{I} X(t) dW(t)=\sum_{n=0}^{\infty}\int_{I} I_n(f_{n,t})dW(t)\\=\sum_{n=0}^{\infty}n! \int_{I}\int_{S_n}f_{n,t}(t_1,\ldots,t_n) dW(t_1)\ldots dW(t_n) dW(t)\\=\sum_{n=0}^{\infty}(n+1)! \int_{I}\int_{S_n}f_{n,S}(t_1,\ldots,t_n,t) dW(t_1)\ldots dW(t_n) dW(t)\\=\sum_{n=0}^{\infty}(n+1)! J_{n+1}(f_{n,S}) =\sum_{n=0}^{\infty}  I_{n+1}(f_{n,S}).
\end{multline*}

:::

## The Skorokhod integral

%

The last term appearing in the equality is what we will call the Skorokhod integral.

::: {#def-1}

Let $X(t)\in L^2(\Omega,\Ff_\infty)$ be a  stochastic process such that

$$
\delta(X):=\int_{I} X(t)\delta W(t):=\sum_{n=0}^{\infty} I_{n+1}(f_{n,S})\in L^2(\Omega).
$$

Then we will say that $X$ has Skorokhod integral $\delta(X)$ and write $X\in \rm{dom}
\delta)$.

:::

As we saw in the previous theorem the Skorokhod integral is equal to the Itô integral for all stochastic processes in $\mathbb{L}^2(I\times\Omega)$. However, it may also be defined for non-adapted stochastic processes. In fact, by using the orthogonality of the iterated integrals (what we called *Itô's* $n$-*th isometry* in the last post [@Chaosblog], we deduce the following).

::: {#prp-1}

A stochastic process $X(t)\in L^2(\Omega,\Ff_\infty)$ has a Skorokhod integral iff

$$
\sum_{n=0}^{\infty} (n+1)!\|f_{n,S}\|^2_{L^2([0,T]^{n+1})}<\infty.
$$

:::

::: {.proof}

By Itô's $n$-th isometry we have that

$$
\norm{\delta(X)}^2_{L^2(\Omega)}=\sum_{n=0}^{\infty}  \norm{I_{n+1}(f_{n,S})}_{L^2(\Omega)}^2=\sum_{n=0}^{\infty} (n+1)!\norm{f_{n,S}}_{L^2(I^{n+1})}^2.
$$

:::

Of course, a priori the above condition is not that easy to check for a given function as it involves calculating the chaos expansion for the given process $X$. In some cases however it is possible, to consider for example the stochastic process defined by $X(t)=W(T)$ on the interval $I=[0,T]$. Then we have that

$$
X(t)=\int_{0}^T dW(t)=I_1(1).
$$

Thus, for all $t\in I$ we have that

$$
f_1=1;\quad f_n=0\quad\forall n \in \N \setminus \{1\}  .
$$

So $X\in \rm{dom}
\delta)$ with

$$
\delta(X)= I_2(1)=\int_{0}^T\int_{0}^t dW(t_1)dW(t)=\int_{0}^T W(t) dW(t)= \frac{1}{2}(W^2(T)-T).
$$

Note however that the Itô integral of $W(T)$ is undefined as it is not  $\Ff_t$ adapted. Since the Skorokhod integral of $1$ is equal to  $W(T)$, the above example shows how one cannot simply ``pull out constants in $t$'' in the sense that, if $G$ is a random variable independent of  $t$ and  $X(t)=G\cdot u(t)$, then

$$
\int_{I} X(t) \delta W(t)=\int_{I}G\cdot u(t)\delta W(t) \neq G\int_{I}u(t) dW(t).
$$

Though this may seem unintuitive, it is a consequence of the fact that, even though $f_i$ may not depend on  $t$, the terms

$$
g(t):=\int_{0}^t\int_{0}^{t_{n}}\cdots \int_{0}^{t_2} f_i dW(t_1)\cdots dW(t_{n-1})dW(t_n)
$$

can depend on $t$. Despite this, the Skorokhod integral still maintains some of the natural properties we associate with integration.

::: {#prp-2}

Let $X(t), Y(t)\in \rm{dom}
\delta)$,$\lambda \in \R$. Then it holds that
- $X(t)+ \lambda Y(t) \in \rm{dom}
\delta)$with$\delta(X+\lambda Y)=\delta(X)+\lambda \delta(Y)$.
- $\E[\delta(X)]=0$.
- $X\cdot 1_A \in \rm{dom}
\delta)$for any measurable subset$A \subset I$. Furthermore, if$A \cup B =I$ then

$$
\int_{A}X(t) \delta W(t)+ \int_{B}X(t)\delta W(t):=\delta(X\cdot 1_A)+\delta(X\cdot 1_B)=\delta(X).
$$

:::

::: {.proof}

	The first property is a consequence of the chaos expansion's linearity (which is itself  a consequence of the linearity of iterated Itô integration). The second is due to the expectation of the Itô integral being $0$. The final property is a consequence of the fact that the chaos expansion of $X\cdot 1_A$ is
	
$$
X\cdot 1_A=\sum_{n=0}^{\infty} I_{n}([f_n 1_A]_S).
$$

	Which shown by the equivalent characterization of Skorokhod functions that $X\cdot 1_A\in \rm{dom}
\delta)$. The final property is a consequence of the previously proved linearity.

:::

We now know what the Skorokhod expansion is, how to characterize it, and its main properties, in the next post we will construct the Malliavin derivative as its adjoint.

## References

::: {#refs}
:::
