---
title: "MC 7: The Ornstein-Uhlenbeck Semigroup"
author: "Liam Llamazares--Elias"
date: "date"
categories: [Malliavin Calculus]
description: "Part 7 of the series on Malliavin calculus"
bibliography: biblio.bib
format:
  html:
    css: /custom_theorems.css
    toc: true
    number-sections: true
    html-math-method: mathjax
    include-in-header:
      text: |
        <script>
        window.MathJax = {
          tex: {
            tags: "ams",
            macros: {
              A: "\\mathbb{A}",
              Aa: "\\mathcal{A}",
              Bb: "\\mathcal{B}",
              C: "\\mathbb{C}",
              Cc: "\\mathcal{C}",
              Dd: "\\mathcal{D}",
              E: "\\mathbb{E}",
              Ee: "\\mathcal{E}",
              F: "\\mathbb{F}",
              Ff: "\\mathcal{F}",
              Gg: "\\mathcal{G}",
              Hh: "\\mathcal{H}",
              II: "\\mathbb{I}",
              Id: "\\bm{I}",
              Ii: "\\mathcal{I}",
              Im: "\\bm{Im}",
              Jj: "\\mathcal{J}",
              K: "\\mathbb{K}",
              KL: ["\\rm{KL}\\left(#1 \\| #2\\right)", 2],
              Kk: "\\mathcal{K}",
              LL: "\\mathbb{L}",
              Ll: "\\mathcal{L}",
              M: "\\mathbb{M}",
              Mm: "\\mathcal{M}",
              N: "\\mathbb{N}",
              Nn: "\\mathcal{N}",
              Oo: "\\mathcal{O}",
              PP: "\\mathbb{P}",
              Pp: "\\mathcal{P}",
              Q: "\\mathbb{Q}",
              Qq: "\\mathcal{Q}",
              R: "\\mathbb{R}",
              Rr: "\\mathcal{R}",
              Ss: "\\mathcal{S}",
              T: "\\mathbb{T}",
              Th: "{\\bm{\\theta}}",
              Thh: "{\\bm{\\Theta}}",
              Tt: "\\mathcal{T}",
              Uu: "\\mathcal{U}",
              Vv: "\\mathcal{V}",
              W: "\\mathbb{W}",
              Ww: "\\mathcal{W}",
              X: "\\mathbb{X}",
              Xx: "\\mathcal{X}",
              Yy: "\\mathcal{Y}",
              Z: "\\mathbb{Z}",
              Zz: "\\mathcal{Z}",
              abs: ["{\\left| #1 \\right|}", 1],
              alf: "{\\alpha}",
              b: ["{\\bm{#1}}", 1],
              bm: ["\\boldsymbol{#1}", 1],
              br: ["\\left\\langle#1\\right\\rangle", 1],
              bt: "\\beta",
              co: ["\\overset{\\circ}{#1}", 1],
              d: "\\mathrm{d}",
              diag: ["\\operatorname{diag}\\left(#1\\right)", 1],
              dx: "\\,\\mathrm{d}x",
              dy: "\\,\\mathrm{d}y",
              eps: "\\varepsilon",
              et: "{\\bm{\\eta}}",
              ex: ["\\mathrm{exp}\\left(#1\\right)", 1],
              fk: ["\\mathfrak{#1}", 1],
              fracc: ["{#1}/{#2}", 2],
              frc: ["\\left(#2)^{-1}(#1\\right)", 2],
              iso: "\\xrightarrow{\\sim}",
              ker: "\\bm{ker}",
              mat: ["\\begin{bmatrix}{#1}\\end{bmatrix}", 1],
              mathbbm: ["\\mathbb{#1}", 1],
              mathds: ["\\mathbb{#1}", 1],
              norm: ["\\left\\lVert #1 \\right\\rVert", 1],
              om: "\\omega",
              postref: ["\\href{https://nowheredifferentiable.com/posts/#1/}{#3}", 3],
              proj: "\\mathrm{proj}",
              qb: ["\\left[#1\\right]", 1],
              qp: ["\\left(#1\\right)", 1],
              qt: ["\\left(#1\\right)", 1],
              red: ["{\\color{red}#1}", 1],
              rm: ["\\mathrm{#1}", 1],
              set: ["\\left\\{#1\\right\\}", 1],
              star: "*",
              tl: ["\\widetilde{#1}", 1],
              tll: ["\\widetilde{#1}", 1],
              vol: "\\mathrm{vol}",
              wh: ["\\widehat{#1}", 1],
              x: "\\bm{x}",
              xxi: "{\\bm{\\xi}}",
              y: "\\bm{y}"
            }
          }
        };
        </script>
---

##  Three line summary

	

- There is a natural extension of the Laplacian to the Wiener space.

- The Laplacian generates the Ornstein-Uhlenbeck semigroup.

- The Ornstein-Uhlenbeck semigroup in finite dimensions is generated by the Ornstein-Uhlenbeck process, from which it derives its name.

	

## The Laplacian of a random variable

	First, we give some finite-dimensional motivation. Suppose that $f\in C_c^\infty(\R^d\to\R^d)$ and $g\in C_c^\infty(\R^d)$. Then an integration by parts shows that the adjoint of the gradient
	in $L^2(\R^d)$ is minus the divergence. That is,
	
$$
\int_{\R^d}f(x) \cdot \nabla g(x) dx=-\int_{\R^d}(\nabla\cdot  f(x)) g(x) dx.
$$

	Then, we define the Laplacian as minus the adjoint of the gradient $\nabla$ composed with the gradient
	
$$
\Delta := -\nabla^*\circ \nabla .
$$

	Which gives the familiar $$\Delta_{\R^d} =\nabla\cdot \nabla=\partial_1^2+\ldots+\partial _d^2$$.

	Of course, this is all well and good when the domain of $f,g$ is a finite-dimensional space. Otherwise, there is no Lebesgue measure.	We now move to what is our base case in our series of blog posts and consider a probability space $(\Omega,\mathbb{P},\mathcal{F}_t)$ where $\Ff_t$ is generated by a Wiener process $W_t$. Then, as we have seen previously (link)
	the Skorokhod integral $\delta$ is the adjoint of the Malliavin derivative $D$ so we would like to define
	
$$
\Delta  := -\delta \circ D.
$$

	On what kind of random variables can we define this? Well let us take $X=\sum_{n=0}^{\infty}  I_n(f_n)$ with a rapidly decaying chaos expansion, then
	
$$
\Delta X=-\delta (DX)=-\delta \left(\sum_{n=1}^\infty nI_{n-1}(f_n(\cdot ,t))\right)=-\sum_{n=1}^\infty nI_{n}(f_n).
$$

	All we require for this expression to make sense is that- the right-hand side is in $L^2(\Omega)$. That is, by Ito's $n$-th isometry (link), that
	
$$
\sum_{n=0}^\infty n^2 \norm{f_n}_{L^2(I_n)}< \infty.
$$

	Is this a space we've dealt with before? Well if we recall our old spaces $\mathbb{D}^{k,p}$  (link). Then we have that
	\begin{multline*}
		\int_{I^2}\norm{D_{t,s}X}_{L^2(\Omega)}^2 ds d t=\int_{I^2}\norm{\sum_{n=2}^\infty n(n-1)I_{n-2}(f_n(\cdot ,s,t))}_{L^2(\Omega)}^2\\=\int_{I^2}\sum_{n=2}^\infty n^2(n-1)^2(n-2)!\norm{f_n(\cdot ,s,t)}_{L^2(I_{n-2})}^2=\sum_{n=2}^\infty n(n-1)n!\norm{f_n(\cdot ,s,t)}_{L^2(I_n)}^2.
	\end{multline*}
	Where analogous calculations go through if we have more derivatives to get the terms $n(n-1)\cdots (n-(k-1))$. This shows that
	
$$
\mathbb{D}^{k,p}:=\left\{X\in L^2(\Omega):\quad \norm{X}_{\mathbb{D}^{k,2}}=\sum_{n=0}^\infty n^kn! \norm{f_n}_{L^p(I_n)}< \infty\right\} .
$$

	Thus, the domain of $\Delta$ is exactly  $\mathbb{D}^{2,2}$. This is quite pleasing as, as we have observed earlier, the spaces $\mathbb{D}^{k,p}$ mimic the Sobolev spaces $W^{k,p}$, when $p=2$ this resemblance is quite strong
	as we have that the norm on  $H^k:=W^{k,2}$ is
	
$$
\norm{f}_{H^k\R^d)}=\int_{\R^d}\br{\xi }^k \hat{f}(\xi )^2d\xi .
$$

	Which is formally equal to the one just derived for $\mathbb{D}^{k,2}.$ It is very interesting to observe that, directly from the definition, we obtain a basis of eigenvalues of $\Delta$. Let us define
	
$$
H_n:=\{X\in L^2(\Omega): X=I_n(f_n),\quad \text{for some } f_n \in L^2_S(I^n)  \} .
$$

	That is, $H_n$ are the random variables that only have the  $n$-th term in their chaos expansion to be non-zero. Then by the chaos expansion theorem, we know that
	
$$
L^2(\Omega)=\overline{\oplus_{n=0}^\infty H_n}.
$$

	And by construction of the Laplacian, $\Delta e_n=-n e_n$ for every $e_n \in H_n$. In fact, by the uniqueness of the chaos expansion, the elements of $H_n$ for some  $n \in \N$ are the unique eigenvectors of $\Delta .$
	

## The Ornstein-Uhlenbeck semigroup

	As it turns out, $\Delta$ defines a semigroup
	

::: {#def-1}

The *Ornstein-Uhlenbeck semigroup* is the family of operators $\Phi(t):L^2(\Omega)\to L^2(\Omega)$

$$
\Phi(t)X:=\sum_{n=0}^{\infty}  e^{-nt}I_n(f_n),  \quad\forall t\in I.
$$

:::

	The term $e^{-nt}$ is quite reminiscent of the semigroup for the heat equation
	
$$
e^{t\Delta }u_0:=\int_{\R^d}e^{-4 \pi^2 \xi^2t}\widehat{u_0}(\xi ) d\xi,
$$

	and will cause an analogous smoothing effect by making the terms in the chaos expansion to decrease	faster. To see that  $\Phi$ defines a semigroup first note that, by the linearity of the iterated integrals,
	
$$
\Phi(t)X:=\sum_{n=0}^{\infty}  I_n(e^{-nt}f_n).
$$

	So as a result
	
$$
\Phi(t+s)X=\sum_{n=0}^{\infty}  e^{-nt}I_n(e^{-ns}f_n)=\sum_{n=0}^{\infty}  \Phi(t)\Phi(s)X.
$$

	Which shows that $\Phi(t+s)=\Phi(t)\circ \Phi(s)$. Finally, note that
	
$$
\frac{\Phi(t)X-X}{t}=\sum_{n=0}^{\infty} \left(\frac{e^{-nt}-1}{nt} \right)nI_n(f_n)\to -\sum_{n=0}^{\infty}  nI_n(f_n)=\Delta X \in L^2(\Omega)  .
$$

	Where the commutation under the integral sign (with the counting measure) is justified as $(e^{-nt}-1)/(nt)$ is uniformly bounded in $n$.
	There's an explicit formula for $\Phi(t)$.
	

::: {#prp-1 name="Mehler's formula"}

Let $(\Omega,\Ff_t,\gamma  )$ be the Wiener space, then

$$
\Phi(t)X(\omega)=\int_{\Omega}X\left(e^{-t}\omega+\sqrt{1-e^{-2t}}\eta\right) \d \gamma  (\eta)\in L^2(\Omega).
$$

:::

	The  proof is technical and can be found in  Nualart's book [@nualart2018introduction] on  page 74. Let us try to understand the formula and also the reason for the name of the semigroup. We consider as at the beginning of this post the finite-dimensional case but now with some Gaussian measure $\mu$
	
$$
\mu(A) := \frac{1}{(2\pi)^{d/2}} \int_{A} e^{-\frac{\norm{x}^2}{2}} dx
$$

	Then, integration by parts shows that
	
$$
\begin{aligned}
\int_{\R^d}f(x) \cdot \nabla g(x) d\mu(x) & =-\int_{\R^d}\nabla\cdot  \left(e^{-\frac{\norm{x}^2}{2} }f(x)\right) \nabla g(x) dx \\&=\int_{\R^d}(x\cdot f(x)-\nabla\cdot f(x)) d\mu (x).
\end{aligned}
$$

	That is, the adjoint of the gradient in $L^2(\R^d,\mu )$ is $x\cdot -\nabla\cdot$. Notice that we get the extra term that corresponds to multiplication by $x\cdot$.As a result, the Laplacian on $L^2(\R^d, \mu )$ is given by
	
$$
\Delta_\mu =\nabla\cdot \nabla-x\cdot \nabla .
$$

	Furthermore, by Itô's formula, $\Delta_\mu$ is the generator of the SDE
	
$$
dX(t)=-X(t)d t+ \sqrt{2}dW(t)
$$

	Let us write $X_x$ for the solution to the above SDE with initial data  $x \in \R^d$
	That is, if we define $$P_tX(x):=E[\varphi(X(t))],$$ then
	
$$
\partial _tP_tX(x)=\Delta_\mu P_tX(x) .
$$

	The process $X$ that solves the SDE above is known as the *Ornstein-Uhlenbeck process* and, by the theory of linear SDEs, is given by
	
$$
X_x(t)=e^{-t}x+\sqrt{2} \int_{0}^te^{s-t} dW(s).
$$

	Since
	
$$
\sqrt{2} \int_{0}^te^{s-t} dW(t)\sim \sqrt{2} e^{-t}\Nn\left(0,\norm{e^\cdot }^2_{L^2([0,t])}\right)=\sqrt{1-e^{-2t}}\Nn(0,1)
$$

	We deduce that for each fixed $t$ we can find $\eta  \sim \Nn(0,1)$ with
	
$$
X(t)=e^{-t}x+\sqrt{1-e^{-2t}}\eta .
$$

	We then get that
	
$$
P_t \varphi(x)=\E\left[\varphi\left(e^{-t}x+\sqrt{1-e^{-2t}}\eta  \right)\right]
$$

	And by taking $\varphi=Id$ we recover Mehler's formula. This correspondence is expanded on in chapter $7$ of Hairer's notes [@hairer2009introduction].

## References

::: {#refs}
:::
