---
title: "MC 4: The Malliavin derivative, part 2"
author: "Billy Summers"
date: "2022-07-02"
categories: [Malliavin Calculus]
description: "Part 4 of the series on Malliavin calculus"
format:
  html:
    css: /custom_theorems.css
    toc: true
    number-sections: true
    html-math-method: mathjax
    include-in-header:
      text: |
        <script>
        window.MathJax = {
          tex: {
            tags: "ams",
            macros: {
              A: "\\mathbb{A}",
              Aa: "\\mathcal{A}",
              Bb: "\\mathcal{B}",
              C: "\\mathbb{C}",
              Cc: "\\mathcal{C}",
              Dd: "\\mathcal{D}",
              E: "\\mathbb{E}",
              Ee: "\\mathcal{E}",
              F: "\\mathbb{F}",
              Ff: "\\mathcal{F}",
              Gg: "\\mathcal{G}",
              Hh: "\\mathcal{H}",
              II: "\\mathbb{I}",
              Id: "\\bm{I}",
              Ii: "\\mathcal{I}",
              Im: "\\bm{Im}",
              Jj: "\\mathcal{J}",
              K: "\\mathbb{K}",
              KL: ["\\rm{KL}\\left(#1 \\| #2\\right)", 2],
              Kk: "\\mathcal{K}",
              LL: "\\mathbb{L}",
              Ll: "\\mathcal{L}",
              M: "\\mathbb{M}",
              Mm: "\\mathcal{M}",
              N: "\\mathbb{N}",
              Nn: "\\mathcal{N}",
              Oo: "\\mathcal{O}",
              PP: "\\mathbb{P}",
              Pp: "\\mathcal{P}",
              Q: "\\mathbb{Q}",
              Qq: "\\mathcal{Q}",
              R: "\\mathbb{R}",
              Rr: "\\mathcal{R}",
              Ss: "\\mathcal{S}",
              T: "\\mathbb{T}",
              Th: "{\\bm{\\theta}}",
              Thh: "{\\bm{\\Theta}}",
              Tt: "\\mathcal{T}",
              Uu: "\\mathcal{U}",
              Vv: "\\mathcal{V}",
              W: "\\mathbb{W}",
              Ww: "\\mathcal{W}",
              X: "\\mathbb{X}",
              Xx: "\\mathcal{X}",
              Yy: "\\mathcal{Y}",
              Z: "\\mathbb{Z}",
              Zz: "\\mathcal{Z}",
              abs: ["{\\left| #1 \\right|}", 1],
              alf: "{\\alpha}",
              b: ["{\\bm{#1}}", 1],
              bm: ["\\boldsymbol{#1}", 1],
              br: ["\\left\\langle#1\\right\\rangle", 1],
              bt: "\\beta",
              co: ["\\overset{\\circ}{#1}", 1],
              d: "\\mathrm{d}",
              diag: ["\\operatorname{diag}\\left(#1\\right)", 1],
              dx: "\\,\\mathrm{d}x",
              dy: "\\,\\mathrm{d}y",
              eps: "\\varepsilon",
              et: "{\\bm{\\eta}}",
              ex: ["\\mathrm{exp}\\left(#1\\right)", 1],
              fk: ["\\mathfrak{#1}", 1],
              fracc: ["{#1}/{#2}", 2],
              frc: ["\\left(#2)^{-1}(#1\\right)", 2],
              iso: "\\xrightarrow{\\sim}",
              ker: "\\bm{ker}",
              mat: ["\\begin{bmatrix}{#1}\\end{bmatrix}", 1],
              mathbbm: ["\\mathbb{#1}", 1],
              mathds: ["\\mathbb{#1}", 1],
              norm: ["\\left\\lVert #1 \\right\\rVert", 1],
              om: "\\omega",
              postref: ["\\href{https://nowheredifferentiable.com/posts/#1/}{#3}", 3],
              proj: "\\mathrm{proj}",
              qb: ["\\left[#1\\right]", 1],
              qp: ["\\left(#1\\right)", 1],
              qt: ["\\left(#1\\right)", 1],
              red: ["{\\color{red}#1}", 1],
              restr: ["\\left.#1\\right|{#2}", 2],
              rm: ["\\mathrm{#1}", 1],
              set: ["\\left\\{#1\\right\\}", 1],
              star: "*",
              tl: ["\\widetilde{#1}", 1],
              tll: ["\\widetilde{#1}", 1],
              vol: "\\mathrm{vol}",
              wh: ["\\widehat{#1}", 1],
              x: "\\bm{x}",
              xxi: "{\\bm{\\xi}}",
              y: "\\bm{y}"
            }
          }
        };
        </script>
---

## The Malliavin derivative as a Fr\'{e

chet derivative}
Let $C_0([0, T])$ be the Banach space of all continuous functions $f \colon [0,
		T] \to \R$such that$f(0) = 0$. On this space, we can associate a special
Borel probability measure $\mu$ such that $W_t(\omega) := \omega(t)$ is a
Brownian motion. Given a random variable on $C_0([0, T])$, i.e. a
$\mu$-measurable function $X \colon C_0([0, T]) \to \R$, we want to know how
the value $X(\omega)$ changes upon perturbing the path $\omega$ by a small
quantity $\gamma \in C_0([0, T])$. This can be described by the Fr\'{e}chet
derivative $\nabla{X}(\omega)$, which is a bounded linear map $C_0([0, T]) \to
	\R$, i.e. a member of the dual space$C_0([0, T])^*$, giving the best linear
approximation to the difference $X(\omega + \gamma) - X(\omega)$. Formally,
$\nabla{X}$ satisfies
\[
	X(\omega + \gamma)
	= X(\omega)
	+ \br{\nabla{X}(\omega), \gamma}
	+ \rm{o}(\norm{\gamma}_{C_0([0, T])}).
\]
If $X$ has a Fr\'{e}chet derivative $\nabla{X} \colon C_0([0, T]) \to C_0([0,
			T])^*$, we say it is *Fr\'{e}chet differentiable*.

Within the Banach space $C_0([0, T])$ lies a Hilbert space $H$ of distinguished
elements. This is the space of paths of the form
\[
	\gamma(t) = \int_0^t \psi(s) \, \d{s}
\]
for some $\psi \in L^2([0, T])$. In other words, it is the space of $W^{1, 2}$
functions on $[0, T]$ starting at 0. Its inner product is given by
\[
	(\gamma_1, \gamma_2)_H = (\dot{\gamma}_1, \dot{\gamma}_2)_{L^2([0, T])}.
\]
$H$ is continuously imbedded in $C_0$ by the theory of Sobolev spaces. We call
$H$ the *Cameron-Martin space*. It acts in some sense as the heart
of $C_0([0, T])$ with the probability measure $\mu$, with its elements having
better analytical properties compared to a general element in $C_0([0, T])$.
Ideally, we could restrict $\mu$ to this space and only work here, but
unfortunately $\mu$ is not a measure on $H$ (in particular, it is not
$\sigma$-additive), forcing us to work in a larger Banach space.

Returning to our Fr\'{e}chet differentiable random variable $X$, given some
path $\omega \in C_0([0, T])$, we consider the restriction of its derivative at
$\omega$ to $H$, namely $\eval*{\nabla{X}(\omega)}_H$. Since $H$ is continously
imbedded in $C_0$, this restriction is an element of $H^*$. Then, as $H$ is a
Hilbert space, the dual space $H^*$ is isomorphic to $H$ through its inner
product, so there exists some $DX(\omega) \in L^2([0, T])$ such
that
\[
	\br{\nabla{X}(\omega), \int_0^\cdot \psi \, \d{t}}
	= \left(\int_0^\cdot D_t{X}(\omega) \, \d{t},
	\int_0^\cdot \psi \, \d{t}\right)_H
	= \int_0^T D_t{X}(\omega) \psi(t) \, \d{t}.
\]
This object $DX$ is precisely the Malliavin derivative of $X$.

## The Skorokhod integral and the Malliavin derivative

Given a stochastic process $(X_t)_{t \in [0, T]} \in L^2([0,T]\times\Omega,
	\d{t}\otimes\P)$such that$X_t$is$\Ff_T$-measurable for all$t \in
	[0, T]$, let
\[
	X_t = \sum_{n = 0}^\infty I_n(f_n(\cdot, t))
\]
be its chaos expansion for some $f_n \in L^2([0, T]^{n + 1})$ symmetric in the
first $n$ variables. Recall we say $X$ is *Skorokhod integrable*, and
define its Skorokhod integral by
\[
	\int_0^T X_t \, \delta{W}_t := \sum_{n = 0}^\infty I_{n + 1}({f}_{n,S}),
\]
whenever this sum converges in $L^2(\Omega)$. The following result is
fundamental.

::: {#thm-1}

The Skorokhod integral and Malliavin derivative are *adjoint* in the
following sense:

Let $(X_t)_{t \in [0, T]}$ be a Skorokhod-integrable. Let $Y \in \mathbb{D}^{1,
2}$ be a Malliavin differentiable random variable. Then
\[
\br{
Y, \int_0^T X_t \, \delta{W}_t
}_{L^2(\Omega)}
= \br{
D{Y}, X
}_{L^2([0,T]\times\Omega)}.
\]
More concretely,
\[
\E\left[
Y \int_0^T X_t \, \delta{W}_t
\right]
= \E\left[
\int_0^T
D_t Y X_t
\, \d{t}
\right].
\]

:::

::: {.proof}

As usual, we apply the definitions in terms of the chaos expansions. Let
\[
	X_t = \sum_{n = 0}^\infty I_n(f_n(\cdot, t))
\]
be the chaos expansion of $X$, and
\[
	Y = \sum_{n = 0}^\infty I_n(g_n)
\]
the chaos expansion of $Y$. Then

$$
\begin{aligned}
\E\left[
		Y \int_0^T X_t \, \delta{W}_t
	\right]
	 & = \E\left[
		\sum_{n = 0}^\infty I_n(g_n)
		\sum_{m = 0}^\infty I_{m + 1}({f}_{m,S})
	\right]                                                                 \\
	 & = \sum_{n = 0}^\infty \sum_{m = 0}^\infty
	\E[I_n(g_n) I_{m + 1}({f}_{m,S})]                               \\
	 & = \sum_{n = 1}^\infty n! (g_n, {f}_{n - 1,S})_{L^2([0, T]^n)},
\end{aligned}
$$

and on the other side,

$$
\begin{aligned}
\E\left[
	\int_0^T D_t{Y} X_t \, \d{t}
	\right]
	 & = \int_0^T \E\left[
		\sum_{n = 1}^\infty n I_{n - 1}(g_n(\cdot, t))
		\sum_{m = 0}^\infty I_m(f_m(\cdot, t))
	\right] \, \d{t}                                            \\
	 & = \int_0^T \sum_{n = 0}^\infty \sum_{m = 0}^\infty
	n \E[
		I_{n - 1}(g_n(\cdot, t)) I_m(f_m(\cdot, t))
	 ] \, \d{t}                                            \\
	 & = \sum_{n = 0}^\infty
	n (n - 1)! \int_0^T
	(g_n(\cdot, t), f_{n - 1}(\cdot, t))_{L^2([0, T]^{n - 1})}
	\, \d{t}                                              \\
	 & = \sum_{n = 1}^\infty
	n! (g_n, f_{n - 1})_{L^2([0, T]^n)}.
\end{aligned}
$$

Finally, by definition of the symmetrization,

$$
\begin{aligned}
(g_n, f_{n - 1,S})_{L^2([0, T]^n)}
	 & = \int_{[0, T]^n}
	g_n(t_1, \dots, t_n)
	\frac{1}{n} \sum_{k = 1}^n
	f_{n-1}(t_1, \dots, t_{k - 1}, t_n, t_{k + 1}, \dots, t_{n - 1}, t_k)
	\, \d{t_1} \cdots \d{t_n}                       \\
	 & = \frac{1}{n} \sum_{k = 0}^n \int_{[0, T]^n}
	g_n(t_1, \dots, t_n)
	f_{n - 1}(t_1, \dots, t_n)
	\, \d{t_1} \cdots \d{t_n}                       \\
	 & = (g_n, f_{n - 1})_{L^2([0, T]^n)},
\end{aligned}
$$

where we change variables $t_k \mapsto t_n, t_n \mapsto t_k$, use the
property that $g_n$ is symmetric, and apply Fubini's theorem.

:::

::: {#rem-1}

The symbol $\delta$ is often used for a divergence-like operator in Hodge
theory. The analogy with our case is that in the Hodge situation, $\delta$
is defined via a duality formula which looks like $\br{d{\alpha},
\beta} = \br{\alpha, \delta{\beta}}$, where$d$ is the exterior
derivative on differential forms. Indeed, even in vector calculus, the
negative of the divergence is in some sense adjoint to the gradient:
\[
\int_\Omega \nabla\cdot{f} \phi \, \d{x}
= - \int_\Omega f \cdot \nabla{\phi} \, \d{x}
\]
whenever $\phi$ has zero boundary. So, in a sense, the Skorokhod integral is
just a divergence operator.

:::

Using this, we can immediately prove the following:

::: {#cor-1}

Let $(X^n)_{n \in \N}$ be a sequence of Skorokhod-integrable stochastic
processes. Suppose there exist $X \in L^2([0,T]\times\Omega)$ and $Y
\in L^2(\Omega)$such that$X^N \to X$in$L^2([0,T]\times\Omega)$, and
$\delta{X^N} \to Y$ in $L^2(\Omega)$. Then $X$ is Skorokhod integrable, and
$\delta{X^N} \to \delta{X}$.

:::

::: {.proof}

Recall that Skorokhod integrability of $X$ can be expressed in terms of
convergence of the series
\[
	\sum_{n = 0}^\infty
	(n + 1)! \norm{{f}_{n,S}}_{L^2([0, T]^{n + 1})}^2,
\]
where $f_n(\cdot, t)$ are the components of the chaos expansion of $X$.
Since $X^N \to X$ strongly in $L^2$, and each $X^N$ is Skorokohod
integrable, the components of their chaos expansions must satisfy the above
condition, and we can take limits.

Let $Z \in \mathbb{D}^{1, 2}$. Then by adjointness,
\[
	(Z, \delta{X^N})_{L^2(\Omega)}
	= (DZ, X^N)_{L^2([0,T]\times\Omega)}.
\]
Taking limits on both sides and using adjointness on the limiting
objects gives us
\[
	(Z, Y)_{L^2(\Omega)}
	= (DZ, X)_{L^2([0,T]\times\Omega)}
	= (Z, \delta{X})_{L^2(\Omega)}.
\]
Then, since $\mathbb{D}^{1, 2}$ is dense in $L^2(\Omega)$, we see that $Y =
	\delta{X}$ a.s., as required.

:::

::: {#rem-2}

Perhaps a more intuitive way to say the Skorokhod integral is ``closable''
in the book's words is that it is sequentially continuous as a map
$D(\delta) \subseteq L^2([0,T]\times\Omega) \to L^2(\Omega)$ with
respect to the strong $L^2$ topology in its domain and weak $L^2$ topology
in its codomain.

:::

::: {#thm-2}

Let $X \in L^2([0,T]\times\Omega)$ be a Skorokhod integrable random
process, and let $Y \in \mathbb{D}^{1, 2}$ be such that $YX$ is also Skorokhod
integrable. Then
\[
Y \int_0^T X_t \, \delta{W}_t
= \int_0^T Y X_t \, \delta{W}_t + \int_0^T D_t Y X_t \, \d{t}
\]
almost surely.

:::

::: {.proof}

Suppose $Y$ has finite chaos expansion, and choose some $Z \in \mathbb{D}^{1, 2}$
also with finite chaos expansion. Then by adjointness and the product rule,

$$
\begin{aligned}
\E\left[
		Z \int_0^T Y X_t \, \delta{W}_t
	\right]
	 & = \E\left[
	\int_0^T D_t{Z} Y X_t \, \d{t}
	\right]                   \\
	 & = \E\left[
	\int_0^T (D_t(YZ) - Z D_t{Y}) X_t \, \d{t}
	\right]                    \\
	 & = \E\left[
		YZ \int_0^T X_t \, \delta{W}_t
	  \right] - \E\left[
	Z \int_0^T D_t{Y} X_t \, \d{t}
	\right].
\end{aligned}
$$

Since the set of all test functions $Z \in \mathbb{D}^{1, 2}$ with finite chaos
expansion is dense in $L^2(\Omega)$, we conclude the result for $Y$ with
finite chaos expansion. For general $Y$, we approximate.

:::

::: {#rem-3}

A similar formula crops up in vector calculus, namely the following:
\[
\nabla\cdot(fX) = \nabla{f} \cdot X + f \nabla\cdot{X},
\]
where $f$ is a scalar function and $X$ a vector field. Again, in the above
theorem, the Malliavin derivative takes the place of the gradient, the
Skorokhod integral take the place of the divergence, and the usual inner
product on $\R^n$ (the dot product) is replaced with the $L^2([0, T])$
inner product. There is a sign difference owing to the fact the adjointness
in the Malliavin case does not induce a sign change, unlike in the vector
calculus case (see the remark above).

:::

::: {#thm-3}

Let $X \in L^2([0,T]\times\Omega)$ be a stochastic process such that
for all $s \in [0, T]$, $X_s$ is in $\mathbb{D}^{1, 2}$, $D{X_s}$ is
Skorokhod integrable, and
\[
\int_0^T DX_s \, \delta{W}_s \in L^2([0,T]\times\Omega).
\]
Then $\delta{X}$ lies in $\mathbb{D}^{1, 2}$, and
\[
D_t(\delta{X}) = \int_0^T D_t{X_s} \, \delta{W}_s + X_t.
\]

:::

::: {#rem-4}

The technical constraints in the theorem above are an unfortunate
consequence of the fact the Skorokhod and Malliavin operators $\delta$ and
$D$ are not defined on the full space $L^2([0,T]\times\Omega)$ and
$L^2(\Omega)$ respectively - we have to ensure an operator throws us to the
right spot before we can consider applying the other one.

Note that this theorem is simply an expression of the Malliavin derivative
and Skorokhod integral's failure to commute, with the error simply being
the identity on $L^2(\Omega \times [0, 1])$. That is,
\[
D\delta = \delta D + \rm{id}.
\]
This contrasts with our vector
calculus analogy, where the divergence and gradient most certainly commute
(assuming enough regularity).

:::

## References

::: {#refs}
:::
