---
title: "The Itô integral"
author: "Liam Llamazares--Elias"
date: "2022-05-22"
categories: [Stochastic Calculus, Ito Integral]
description: "Can you really construct this thing?"
bibliography: biblio.bib
format:
  html:
    toc: true
    number-sections: true
    html-math-method: mathjax
    include-in-header:
      text: |
        <script>
        window.MathJax = {
          tex: {
            tags: "ams",
            macros: {
              A: "\\mathbb{A}",
              Aa: "\\mathcal{A}",
              Bb: "\\mathcal{B}",
              C: "\\mathbb{C}",
              Cc: "\\mathcal{C}",
              Dd: "\\mathcal{D}",
              E: "\\mathbb{E}",
              Ee: "\\mathcal{E}",
              F: "\\mathbb{F}",
              Ff: "\\mathcal{F}",
              Gg: "\\mathcal{G}",
              Hh: "\\mathcal{H}",
              II: "\\mathbb{I}",
              Id: "\\bm{I}",
              Ii: "\\mathcal{I}",
              Im: "\\bm{Im}",
              Jj: "\\mathcal{J}",
              K: "\\mathbb{K}",
              KL: ["\\rm{KL}\\left(#1 \\| #2\\right)", 2],
              Kk: "\\mathcal{K}",
              LL: "\\mathbb{L}",
              Ll: "\\mathcal{L}",
              M: "\\mathbb{M}",
              Mm: "\\mathcal{M}",
              N: "\\mathbb{N}",
              Nn: "\\mathcal{N}",
              Oo: "\\mathcal{O}",
              PP: "\\mathbb{P}",
              Pp: "\\mathcal{P}",
              Q: "\\mathbb{Q}",
              Qq: "\\mathcal{Q}",
              R: "\\mathbb{R}",
              Rr: "\\mathcal{R}",
              Ss: "\\mathcal{S}",
              T: "\\mathbb{T}",
              Th: "{\\bm{\\theta}}",
              Thh: "{\\bm{\\Theta}}",
              Tt: "\\mathcal{T}",
              Uu: "\\mathcal{U}",
              Vv: "\\mathcal{V}",
              W: "\\mathbb{W}",
              Ww: "\\mathcal{W}",
              X: "\\mathbb{X}",
              Xx: "\\mathcal{X}",
              Yy: "\\mathcal{Y}",
              Z: "\\mathbb{Z}",
              Zz: "\\mathcal{Z}",
              abs: ["{\\left| #1 \\right|}", 1],
              alf: "{\\alpha}",
              b: ["{\\bm{#1}}", 1],
              bm: ["\\boldsymbol{#1}", 1],
              br: ["\\left\\langle#1\\right\\rangle", 1],
              bt: "\\beta",
              co: ["\\overset{\\circ}{#1}", 1],
              d: "\\mathrm{d}",
              diag: ["\\operatorname{diag}\\left(#1\\right)", 1],
              dx: "\\,\\mathrm{d}x",
              dy: "\\,\\mathrm{d}y",
              eps: "\\varepsilon",
              et: "{\\bm{\\eta}}",
              ex: ["\\mathrm{exp}\\left(#1\\right)", 1],
              fk: ["\\mathfrak{#1}", 1],
              fracc: ["{#1}/{#2}", 2],
              frc: ["\\left(#2)^{-1}(#1\\right)", 2],
              iso: "\\xrightarrow{\\sim}",
              ker: "\\rm{ker}",
              mat: ["\\begin{bmatrix}{#1}\\end{bmatrix}", 1],
              mathbbm: ["\\mathbb{#1}", 1],
              mathds: ["\\mathbb{#1}", 1],
              norm: ["\\left\\lVert #1 \\right\\rVert", 1],
              om: "\\omega",
              proj: "\\mathrm{proj}",
              qb: ["\\left[#1\\right]", 1],
              qp: ["\\left(#1\\right)", 1],
              qt: ["\\left(#1\\right)", 1],
              red: ["{\\color{red}#1}", 1],
              restr: ["\\left.#1\\right|{#2}", 2],
              rm: ["\\mathrm{#1}", 1],
              set: ["\\left\\{#1\\right\\}", 1],
              star: "*",
              supp: "\\operatorname{supp}",
              tl: ["\\widetilde{#1}", 1],
              tll: ["\\widetilde{#1}", 1],
              vol: "\\mathrm{vol}",
              wh: ["\\widehat{#1}", 1],
              x: "\\bm{x}",
              xxi: "{\\bm{\\xi}}",
              y: "\\bm{y}"
            }
          }
        };
        </script>
---

## Three line summary

- The Itô integral is a way of integrating random variables against Brownian motion.

- The Itô integral is well defined for piecewise constant adapted processes $\mathcal{E}$ and turns them isometrically into square integrable continuous martingales ($\Mm_I^2$).

- As a result the Itô integral can be extended isometrically to a function $\overline{\Ee}\to \Mm_I^2$. Furthermore $\overline{\Ee}$ can be characterised explicitly as the square integrable adapted processes that are measurable in time and space.

## Why should I care?

The Itô integral forms the basis of the whole of stochastic calculus. This comprises SDEs, SPDEs. Knowledge of what functions can be integrated and what properties the integrated function has is instrumental. In this post we construct the integral and address both of the preceding issues.

## Notation

Given two measure spaces $(\Omega,\Ff),(\Omega',\Ff')$ we abbreviate that $f:\Omega\to\Omega'$ is measurable between $\Ff$ and $\Ff'$ as
$f:\Ff\to\Ff'.$ Furthermore we will take $I=[0,T]$ or $I=[0,+\infty)$ to be the index set of our stochastic processes and by abuse of notation write $\Ff_\infty$ to mean $\Ff_T$ in the former case and $\Ff_\infty$ in the latter.

## Progressive measurability

Perhaps the best way to understand a $\sigma$-algebra is as a set of available information. With this interpretation we understand $\Ff_t$ as the information available to us by time $t$. A basic property of a stochastic process is that at time $t$ they are determined by this information.

::: {#def-1}

A stochastic process $\{X_t\}_{t\in I}$ valued in a measurable space $(H,\Hh)$ is *adapted* if $X_t : \Ff_t \to \Hh$ for all $t \in I$.

:::

As we will soon see the only stochastic process that can be integrated are the square integrable and progressively measurable. But what does this mysterious term mean?

::: {#def-2}

A stochastic process $\{X_t\}_{t\in I}$ valued in a measurable space $(H,\Hh)$ is *progressively measurable* if its restriction to $[0,t]\times\Omega$ is measurable as a map $$X|_{[0,t]\times\Omega} : \Bb([0,t])\otimes\Ff_t\to \Hh$$ for all $t\in I$.

:::

Whenever we're given a stochastic process and a filtration the first thing to check is that it is adapted. In fact, since $\omega\to(t,\omega)$ is $\Ff_t\to \Bb([0,t])\otimes \Ff_t$ measurable for all $t$ we have that the following holds.

::: {#lem-1}

Progressively measurable processes are adapted.

:::

Additionally, stochastic processes can be viewed path-wise but also be seen as functions of a product space, this leads to the following definition.

::: {#def-3}

We say that a stochastic process $\{X_t\}_{t\in I}$ valued in a measurable space $(H,\Hh)$ is jointly measurable if $$X:\Bb(I)\otimes\Ff_\infty\to \Hh$$
where $\Ff_\infty:=\vee_{t\in I}\Ff_t$.

:::

In the definition of progressive measurability we imposed some kind of measurability, in fact the condition leads to the following

::: {#prp-1 name="Progressive implies jointly measurable"}

Let $I\subset\R$, and $\{X_t\}_{t\in I}$ be progressively measurable. Then it is also jointly measurable.

:::

::: {.proof}

Let  $\{t_n\}_{n\in\N}\subset I$ be a sequence converging to $\sup I$ and with $t_0=T$ if $T<\infty$. Given $A\in\mathcal{H}$ we have that
\begin{multline*}
(X|_{[0,t]\times\Omega})^{-1}(A)\in\Bb([0,t])\otimes\Ff_t\quad\forall t\in I\\ \iff X^{-1}(A)\cap([0,t]\times\Omega)\in\Bb([0,t])\otimes\Ff_t\quad\forall t\in I\\\implies X^{-1}(A)=\bigcup_{n \in  \N}\left(X^{-1}(A)\cap([0,t_n]\times\Omega)\right), \in\Bb(I)\otimes\Ff_\infty.
\end{multline*}

:::

Note however that the converse isn't true, for example if $X$ is constant in $t$ then, for some $B\subset \Omega$

$$
X^{-1}(A)=I\times B, \quad (X|_{[0,t]\times\Omega})^{-1}(A)= [0,t]\times B.
$$

So it suffices to consider some Construction where $B\in\Ff_\infty$ but $B\not\in\Ff_t$.
It is also important to note the following.

::: {#lem-2 name="SDE coefficients are progressive"}

Let $X_t$ be a  progressively measurable stochastic process and let $f:\Bb(I)\times\Hh\to\Gg$ be measurable, then $f(t,X_t)$ is progressively measurable.

:::

::: {.proof}

This follows from writing the map as the composition of $(t,\omega)\mapsto (t,X(t,\omega))$ and $f$. The former map evaluates to a measurable function on $[0,t]\times\Omega$ with respect to $\Bb([0,t])\otimes\Ff_t$, since $(t,\omega)\mapsto t$ is measurable and $(t,\omega)\mapsto X(t,\omega)$ is measurable by the progressive measurability of $X$.

:::

The difference between progressively measurable and adapted is quite subtle. In fact every adapted and jointly measurable stochastic process has a progressively measurable modification (see [@Karatzas1987BrownianMA] page $5$). The proof of this fact is very lengthy and technical. Thus, if $X\in L^2(\Bb(I)\otimes\Ff_\infty)$ (and in particular is jointly measurable) is adapted, we may always choose a representative that is progressively measurable. This leads to some authors giving the definition of the class of Itô integrable functions in terms of joint measurability instead of progressive measurability. In the end both lead to equivalent definition. That said, this technicality is usually of little importance due to the following result.

::: {#lem-3 name="Continuity is progressive"}

Let $\{X_t\}_{t\in I}$ be a left or right continuous stochastic process. Then $X$ is progressively measurable.

:::

::: {.proof}

Fix $t \in I$. We will show that the restriction of $X$ to $[0,t]\times\Omega$ is $\Bb([0,t])\otimes\Ff_t$ measurable. Suppose for example that $X$ is right continuous, then we consider the approximations

$$
X_{s}^{(n)}(\omega)=X_{(k+1)t / 2^{n}}(\omega) \quad \text{ for } \frac{k t}{2^{n}}<s \leq \frac{k+1}{2^{n}} t
$$

and $X_0^{(n)}(\omega) = X_0(\omega)$. 
The pre-image of any set $A\in\Hh$ under $(X^{(n)})|_{[0,t]\times \Omega}$ is of the form

$$
\left(\{0\}\times X_0^{-1}(A)\right) \cup \bigcup_{k=0}^{2^n-1}\left(\left(\frac{k t}{2^n},\frac{(k+1) t}{2^n}\right]\times X_{(k+1)t/2^n}^{-1}(A)\right).
$$

Since $X$ is adapted, $X_{(k+1)t/2^n}^{-1}(A) \in \Ff_{(k+1)t/2^n} \subseteq \Ff_t$, meaning the above set is in $\Bb([0,t])\otimes\Ff_t$. We conclude as by right continuity $\lim_{n \to \infty}X_{s}^{(n)}(\omega)=X_s(\omega)$ for all $s \in [0,t]$. The pointwise limit of measurable functions is measurable. Also we used that, for the same reason, the pointwise limit of progressively measurable functions is progressively measurable.

:::

## Construction of the integral

As for Riemann integration our construction relies on step functions, here called elementary processes.

::: {#def-4}

We say that $f: I \times \Omega \to \R$ is an elementary process if there exist increasing $\set{t_j}_{j=1}^n  \subset I$ and $\xi_j : \Ff_{t_j} \to I$ such that

$$
\begin{aligned}
X_t = \sum_{j=1}^n \xi_{j} \mathbbm{1}_{(t_j,t_{j+1}]}(t),\quad \forall t \in I.
\end{aligned}
$$

:::

::: {#lem-4}

For any $p \in[1, \infty)$, the space of elementary processes $\Ee$ is $L^{p}$-dense in the space $\mathbb{L}^{p}(I\times\Omega)$ of progressively measurable processes. That is, for any $Y \in \mathbb{L}^{p}(I\times\Omega)$ there exists a sequence of elementary processes $V_{n} \in \Ee$ such that
$$
\E\left[\int_{I}\left|Y(t)-V_{n}(t)\right|^{p} dt\right] \longrightarrow 0.
$$

:::

A detailed proof is given in \citet[Chapter 2]{Lalley2013NOTESOT}. This density immediately yields the closure of elementary processes.

::: {#thm-1}

Let $(\Ee,\|\cdot\|_{L^2(I\times\Omega)})$ be the space of elementary stochastic processes adapted to $\{\Ff_t\}_{t\in I}$, equipped with the $L^2(I\times\Omega)$ norm. Its completion is exactly

$$
\mathbb{L}^2(I\times\Omega) := \{X\in L^2(I\times\Omega) \mid X \text{ is progressively measurable}\}.
$$

:::

The proof of this is by the previous approximation result together with the fact that the Ito integral of elementary processes is an isometry and the fact that $\mathbb{L}^2(I\times\Omega)$ is complete. This last property follows from the completeness of the $L^p$ spaces and the fact that pointwise limits of progressively measurable functions are progressively measurable (and from every convergent sequence in $L^p$ we can extract a convergent sub-sequence which must also converge to the $L^p$ limit).
This finally leads us to be able to define the stochastic integral.

::: {#thm-2}

Let $t\in I$ and define for a elementary process $f\in\Ee$ $$\int_{0}^t X dW=\sum_{n=0}^{N-1} X(t_n)(W(t\land t_{n+1})-W(t_n)).$$
Then the above defines an isometry to the space of continuous square integrable martingales $\Mm_I^2$ as

$$
\begin{aligned}
\rm{int }: \left(\mathcal{E},\norm{\cdot }_ {L^2(I\times\Omega)}\right) & \longrightarrow  \left(\mathcal{M}_ I^2,\norm{\cdot }_{L^2(I\times\Omega)}\right) \\
X(t)                                                           & \longmapsto \int_ {0}^t X dW
.
\end{aligned}
$$

Thus, it extends uniquely to the closure $\overline{\Ee}=\mathbb{L}^2(I\times\Omega)$. Furthermore the extension also has image in $\Mm_I^2.$

:::

::: {.proof}

The first part of the proof is a calculation using the definition of integral of elementary process, the adaptedness of $X$ and the definition of  $W$. The second part is slightly more tricky. The fact that $X$ is a martingale is due to  $L^2$ convergence ($L^1$ would suffice). Then, one takes a sequence of elementary processes  $X_n$ converging to  $X$. By the first part one may apply Doob's martingale inequality and $L^2$ convergence to get a measure of the set where the supremum

$$
\sup_{t\in I}  |X_n(t)-X_m(t)|>2^{-k},
$$

which can be made small for $n,m \to\infty$. One can then extract a subsequence and apply Borel-Cantelli to deduce that the above supremum goes to $0$ almost everywhere. This shows that  $X_n$ is almost everywhere Cauchy in  $L^\infty$ and thus converges almost everywhere to some continuous process $Y$. This process must be $X$ by  $L^2$ convergence to  $X$ which concludes the proof.

:::

## References

::: {#refs}
:::
