---
title: "Martingales in Banach spaces"
author: "Liam Llamazares--Elias"
date: "2022-05-23"
categories: [Stochastic Calculus]
description: "Doob's Martingale inequality is cool"
bibliography: biblio.bib
format:
  html:
    toc: true
    number-sections: true
    html-math-method: mathjax
    include-in-header:
      text: |
        <script>
        window.MathJax = {
          tex: {
            tags: "ams",
            macros: {
              A: "\\mathbb{A}",
              Aa: "\\mathcal{A}",
              Bb: "\\mathcal{B}",
              C: "\\mathbb{C}",
              Cc: "\\mathcal{C}",
              Dd: "\\mathcal{D}",
              E: "\\mathbb{E}",
              Ee: "\\mathcal{E}",
              F: "\\mathbb{F}",
              Ff: "\\mathcal{F}",
              Gg: "\\mathcal{G}",
              Hh: "\\mathcal{H}",
              II: "\\mathbb{I}",
              Id: "\\bm{I}",
              Ii: "\\mathcal{I}",
              Im: "\\bm{Im}",
              Jj: "\\mathcal{J}",
              K: "\\mathbb{K}",
              KL: ["\\rm{KL}\\left(#1 \\| #2\\right)", 2],
              Kk: "\\mathcal{K}",
              LL: "\\mathbb{L}",
              Ll: "\\mathcal{L}",
              M: "\\mathbb{M}",
              Mm: "\\mathcal{M}",
              N: "\\mathbb{N}",
              Nn: "\\mathcal{N}",
              Oo: "\\mathcal{O}",
              PP: "\\mathbb{P}",
              Pp: "\\mathcal{P}",
              Q: "\\mathbb{Q}",
              Qq: "\\mathcal{Q}",
              R: "\\mathbb{R}",
              Rr: "\\mathcal{R}",
              Ss: "\\mathcal{S}",
              T: "\\mathbb{T}",
              Th: "{\\bm{\\theta}}",
              Thh: "{\\bm{\\Theta}}",
              Tt: "\\mathcal{T}",
              Uu: "\\mathcal{U}",
              Vv: "\\mathcal{V}",
              W: "\\mathbb{W}",
              Ww: "\\mathcal{W}",
              X: "\\mathbb{X}",
              Xx: "\\mathcal{X}",
              Yy: "\\mathcal{Y}",
              Z: "\\mathbb{Z}",
              Zz: "\\mathcal{Z}",
              abs: ["{\\left| #1 \\right|}", 1],
              alf: "{\\alpha}",
              b: ["{\\bm{#1}}", 1],
              bm: ["\\boldsymbol{#1}", 1],
              br: ["\\left\\langle#1\\right\\rangle", 1],
              bt: "\\beta",
              co: ["\\overset{\\circ}{#1}", 1],
              d: "\\mathrm{d}",
              diag: ["\\operatorname{diag}\\left(#1\\right)", 1],
              dx: "\\,\\mathrm{d}x",
              dy: "\\,\\mathrm{d}y",
              eps: "\\varepsilon",
              et: "{\\bm{\\eta}}",
              ex: ["\\mathrm{exp}\\left(#1\\right)", 1],
              fk: ["\\mathfrak{#1}", 1],
              fracc: ["{#1}/{#2}", 2],
              frc: ["\\left(#2)^{-1}(#1\\right)", 2],
              iso: "\\xrightarrow{\\sim}",
              ker: "\\rm{ker}",
              mat: ["\\begin{bmatrix}{#1}\\end{bmatrix}", 1],
              mathbbm: ["\\mathbb{#1}", 1],
              mathds: ["\\mathbb{#1}", 1],
              norm: ["\\left\\lVert #1 \\right\\rVert", 1],
              om: "\\omega",
              postref: ["\\href{https://nowheredifferentiable.com/posts/#1/}{#3}", 3],
              proj: "\\mathrm{proj}",
              qb: ["\\left[#1\\right]", 1],
              qp: ["\\left(#1\\right)", 1],
              qt: ["\\left(#1\\right)", 1],
              red: ["{\\color{red}#1}", 1],
              restr: ["\\left.#1\\right|{#2}", 2],
              rm: ["\\mathrm{#1}", 1],
              set: ["\\left\\{#1\\right\\}", 1],
              star: "*",
              tl: ["\\widetilde{#1}", 1],
              tll: ["\\widetilde{#1}", 1],
              vol: "\\mathrm{vol}",
              wh: ["\\widehat{#1}", 1],
              x: "\\bm{x}",
              xxi: "{\\bm{\\xi}}",
              y: "\\bm{y}"
            }
          }
        };
        </script>
---

## Three line summary

- Conditional expectations exist in a natural way for simple functions, by taking extensions they also exist for integrable functions to a Banach space $L^1(\Omega\to E)$.

- Using conditional expectations we can define what a martingale is just like in the real case.

- The space of continuous $p$-integrable martingales is a Banach space.

## Why should I care?

Banach valued martingales form the basis of SPDEs. This is because analogously to Itô integration of real-valued processes. Integrating against a Wiener process valued in a Banach space the same will produce a square integrable continuous martingale.

## Conditional expectation

In graduate-level probability courses, given a $\sigma$-algebra $\Gg$ one shows that by applying Radon--Nikodym's theorem, for any real-valued random variable $X\in L^1(\Omega\to \R)$ there exists a conditional expectation $\E_{\Gg}[X]$ verifying that

$$
\int_A \E_{\Gg}[X]=\int_A X,\quad \forall A\in\Gg.
$$

Of course, now that we have created an integral for integral random variables to a Banach space $L^1(\Omega\to E)$ we would like to see whether such a conditional expectation also exists for these functions. If we are given a simple function

$$
X=\sum_{k=1}^n x_k 1_{A_k}, \quad x_k\in E, A_k\in\Gg.
$$

It is a simple calculation to show that, since $1_{A_k}$ are real-valued and thus $\E_{\Gg}[1_{A_k}]$ are well defined, then

$$
\E_{\Gg}[X]=\sum_{k=1}^n x_k \E_{\Gg}[1_{A_k}],
$$

verifies the desired formula. Furthermore, we have that $\mathbb{E}_\mathcal{F}$ is a linear, and pointwise continuous operator with

$$
\left\|\E_{\Gg}[X]\right\|\leq \sum_{k=1}^n \|x_k\| \E_{\Gg}[1_{A_k}]=\E_{\Gg}\left[\sum_{k=1}^n \|x_k\|1_{A_k}\right]=\E_{\Gg}\left[\|X\|\right].
$$

This allows us to show the following:

::: {#thm-1 name="Existence and uniqueness of conditional expectation"}

Let $X\in L^1(\Omega\to E)$ for some Banach space $E$. Then $X$ has a conditional expectation satisfying

$$
\left\|\E_{\Gg}[X]\right\|\leq\E_{\Gg}\left[\|X\|\right].
$$

:::

::: {.proof}

We have already proved the above inequality for simple processes. By our previous post on the [Bochner integral](</posts/Analysis on Banach spaces/Bochner_integral/index.qmd>), we can take $X_n$ converging to $X$ in $L^1(\Omega\to E)$ to obtain that

$$
\begin{aligned}
\left\|\E_{\Gg}[X_n-X_m]\right\|&\leq\E_{\Gg}\left[\|X_n-X_m\|\right]\\&\implies \E[\left\|\E_{\Gg}[X_n]-\E_{\Gg}[X_m]\right\|]\leq \E\left[\|X_n-X_m\|\right]\to 0
\end{aligned}
$$

As a result, $\E_{\Gg}[X_n]$ is a Cauchy sequence in $L^1(\Omega\to E)$ and converges to some function $Y$, passing to the limit in the defining equation for the conditional expectation shows that $Z=\E_\Gg[X]$. Finally, to prove uniqueness we have that if both $Z_1,Z_2$ satisfy

$$
\int_A Z_1=\int_A X=\int_A Z_2,\quad \forall A\in\Gg.
$$

Then using the linearity of the integral we obtain that $w(Z_1)=w(Z_2)$ for all linear functions $w \in E^*$, so $Z_1=Z_2$.

:::

## Martingales

Okay, so we leveraged some inequalities to prove the existence of a conditional expectation. This done, the following definition mimicking the real case is quite natural. Given measurable spaces $(F,\Ff)$ and $(G,\Gg)$, we use the notation $f: \Ff \to \Gg$ to mean $f:(F,\Ff)\to (G,\Gg)$ is measurable.

::: {#def-1}

Let $\{M(t)\}_{t\in I}$ be a stochastic process on $(\Omega, \Ff, \PP)$ with a filtration $\{\Ff_{t}\}_{t \in I}$. The process $M$ is called an $\Ff_{t}$-martingale, if:

1. $M(t)\in L^1(\Omega\to E)$ for all $t\in I$,

2. $M(t):\Ff_{t} \to \Bb(E)$ for all $t\in I$,

3. $\E_{\Ff_{s}}\left[M(t)\right]=M(s)$ for all $s \leq t$.

:::

The concept of submartingale is  defined by replacing the equality in 3. with a $\geq$. Let us abbreviate $\E_{\Ff_t}$ by $\E_t$. Then, as in the real case, we have the following.

::: {#lem-lem:norm-is-submart name="Norm: martingale $\to$ submartingale"}

Let $M(t)$ be a martingale, then $\norm{M(t)}$ is a submartingale.

:::

::: {.proof}

We recall that, by the Hahn Banach theorem, it holds for any metric space that given $y\in E$

$$
\norm{z}=\sup_{\ell\in E^*:\|\ell\|=1}\ell(z)
$$

As a result, by the linearity of the integral and abbreviating the supremum to just $\sup_\ell$,

$$
\begin{aligned}
\|M(s)\|&=\|\E_{s}[M(t)]\|= \sup_\ell \ell\left(\E_{s}[M(t)]\right)=\sup_\ell\|{\E_{s}\left[\ell(M(t))\right]\|}\\
&\leq \E_{s}\left[\sup_\ell\ell(M(t))\right]=\E_{s}\left[\|M(t)\|\right]
\end{aligned}
$$

:::

Let us recall the following result for real-valued martingales [@ccinlar2011probability, Theorem 3.2.6].

::: {#lem-1 name="Doob's maximal Martingale inequality"}

Let $\{X_k\}_{k=1}^\infty$ be a real-valued submartingale. Then it holds that

$$
\norm{\max_{k\in\{1,...,n\}}\abs{X_k}}_{L^p(\Omega)}\leq \frac{p}{p-1}\norm{X_n}_{L^p(\Omega)}
$$

As a consequence, if $X_t,t\in[0,T]$ is left (or right) continuous then

$$
\norm{\max_{t\in[0,T]}X_k}_{L^p(\Omega)}\leq \frac{p}{p-1}\norm{X_T}_{L^p(\Omega)}.
$$

:::

The idea of the above result is that, since $X_k$ is a submartingale, $X_k\lesssim X_{k+1}\lesssim...\lesssim X_n$. Getting from the continuous to the discrete case is possible by using the continuity of $X$ and approximating it on some finer and finer mesh $t_0,...,t_n$. This said, applying Doob's maximal martingale inequality together with @lem-lem:norm-is-submart gives that

::: {#thm-thm:doobs-hilbert name="Maximal Inequality"}

Let $p>1$ and let $E$ be a separable Banach space.
If $M(t)$, is a right-continuous $E$-valued $\mathcal{F}_{t}$-martingale, then

$$
\begin{aligned}
\left(E\left(\sup _{t \in[0, T]}\|M(t)\|^{p}\right)\right)^{\frac{1}{p}} &\leq \frac{p}{p-1} \sup _{t \in[0, T]}\left(E\left(\|M(t)\|^{p}\right)\right)^{\frac{1}{p}} \\
&=\frac{p}{p-1}\left(E\left(\|M(T)\|^{p}\right)\right)^{\frac{1}{p}}
\end{aligned}
$$

:::

::: {.proof}

This follows by using that $\norm{M(t)}$ is a submartingale and Doob's maximal inequality.

:::

Doob's inequality is essentially an equality between different function norms we can place on the space of continuous Martingales and will provide a very powerful tool later on.

::: {#cor-1}

Let $M$ be a (left or right) continuous martingale to a separable Banach space $E$. Then the following are equivalent

- $M\in \hat{L}^\infty([0,T]\to \hat{L}^2(\Omega\to E))$

- $M\in \hat{L}^2(\Omega\to \hat{L}^\infty([0,T]\to E))$

- $\mathbb{E}[\norm{M(T)}^2]<\infty$

Where we recall from the previous post that $\hat{L}^p$ symbolizes that $M$ may not be separately valued and only have an integrable norm. That said, the same reasoning shows that the above result also holds for the integrable $L^p$ spaces.

:::

A useful space of Martingales is as follows

::: {#def-2}

Let $M(t)$ be a $E$ valued martingale with index set $I=[0,T]$, then we define

$$
\mathcal{M}_T^2(E):=\left\{\text{continuous martingales } M:\mathbb{E}[\norm{M(T)}^2]<\infty\right\}
$$

and give it the norm

$$
\norm{M}_{\mathcal{M}_T^2(E)}:=\left(\mathbb{E}[\norm{M(T)}^2]\right)^ \frac{1}{2}
$$

:::

By @thm-thm:doobs-hilbert we have that

$$
\mathcal{M}_T^2(E)\subset \hat{L}^\infty([0,T]\to \hat{L}^2(\Omega\to E))\cap \hat{L}^2(\Omega\to \hat{L}^\infty([0,T]\to E)).
$$

and that any of the norms of these spaces is equivalent to the one set on $\mathcal{M}_T^2(E)$. This is useful in the following result

::: {#prp-1}

Let $E$ be a separable Banach space, then $\mathcal{M}_T^2(E)$ is a Banach space.

:::

::: {.proof}

By the previous observation  and the completeness of the $\hat{L}^p$ spaces proved in the previous post, $\mathcal{M}_T^2(E)$ is a subspace of a Hilbert space. As a result, it is sufficient to show that it is closed. Let $M_n$ converge to $M$. Then, by the equivalence of the norms we have that $M_n(t)\to M(t)\in \hat{L}^1(\Omega\to E)\subset \hat{L}^2(\Omega\to E)$ so that for all $A\in\mathcal{F}_s$

$$
\int_A M(s)d\mathbb{P}=\lim_{n\to\infty}\int_A M_n(s)d\mathbb{P}=\lim_{n\to\infty}\int_A M_n(t)d\mathbb{P}=\int_A M(t)d\mathbb{P}.
$$

This shows that $M$ is a martingale. Furthermore, as was seen in the previous post, there exists a subsequence $M_{n_k}$ such that

$$
\lim_{n\to\infty}{M_{n_k}}(\cdot,\omega)=M(\cdot,\omega)\in \hat{L}^\infty([0,T]\to E)\quad a.e.\quad \omega\in\Omega
$$

Since $M_{n_k}(\cdot,\omega)$ are continuous and continuity is preserved by uniform limits this proves that $M$ is continuous almost everywhere. This concludes the proof.

:::

In future instalments, we will prove that a Wiener process valued in a Hilbert space $H$ belongs to this space and use it to define the stochastic integral that leads to the construction of SPDEs.

::: {#prp-2}

Let $H$ be a separable Hilbert space and $Q$ be a symmetric, non-negative, trace-class operator on $H$. Let $W(t)$ be an $H$-valued $Q$-Wiener process with respect to a filtration $\Ff_t$. Then $W(t) \in \mathcal{M}_T^2(H)$.

:::

::: {.proof}

The process $W(t)$ is adapted by definition. Let $0 \leq s < t \leq T$. Given $A \in \Ff_s$ and $u \in H$, the mapping $x \mapsto \langle x, u \rangle$ is a bounded linear functional. Since $W(t) - W(s)$ is independent of $\Ff_s$, we apply the properties of the Bochner integral to obtain:

$$
\begin{aligned}
\br{ \int_A (W(t)-W(s)) d\mathbb{P}, u  }   &= \int_A \langle W(t)-W(s), u \rangle d\mathbb{P} \\
&= \mathbb{E}[1_A] \mathbb{E}[\langle W(t)-W(s), u \rangle] = 0.
\end{aligned}
$$

This satisfies the definition of conditional expectation, proving $\mathbb{E}[W(t) \mid \Ff_s] = W(s)$, so $W(t)$ is a martingale. Finally, by construction $\mathbb{E}[\|W(t)\|^2] = t \operatorname{Tr}(Q)<\infty$ as $Q$ is trace-class. Continuity is given by the definition of the Wiener process. This concludes the proof.

:::

## References

::: {#refs}
:::
