---
title: "Title"
author: "Liam Llamazares--Elias"
date: "date"
categories: [Malliavin Calculus]
bibliography: biblio.bib
format:
  html:
    css: custom_theorems.css
    toc: true
    number-sections: true
    html-math-method: mathjax
    include-in-header:
      text: |
        <script>
        window.MathJax = {
          tex: {
            tags: "ams",
            macros: {
              A: "\\mathbb{A}",
              Aa: "\\mathcal{A}",
              Bb: "\\mathcal{B}",
              C: "\\mathbb{C}",
              Cc: "\\mathcal{C}",
              Dd: "\\mathcal{D}",
              E: "\\mathbb{E}",
              Ee: "\\mathcal{E}",
              F: "\\mathbb{F}",
              Ff: "\\mathcal{F}",
              Gg: "\\mathcal{G}",
              Hh: "\\mathcal{H}",
              II: "\\mathbb{I}",
              Id: "\\bm{I}",
              Ii: "\\mathcal{I}",
              Im: "\\bm{Im}",
              Jj: "\\mathcal{J}",
              K: "\\mathbb{K}",
              KL: ["\\rm{KL}\\left(#1 \\| #2\\right)", 2],
              Kk: "\\mathcal{K}",
              LL: "\\mathbb{L}",
              Ll: "\\mathcal{L}",
              M: "\\mathbb{M}",
              Mm: "\\mathcal{M}",
              N: "\\mathbb{N}",
              Nn: "\\mathcal{N}",
              Oo: "\\mathcal{O}",
              PP: "\\mathbb{P}",
              Pp: "\\mathcal{P}",
              Q: "\\mathbb{Q}",
              Qq: "\\mathcal{Q}",
              R: "\\mathbb{R}",
              Rr: "\\mathcal{R}",
              Ss: "\\mathcal{S}",
              T: "\\mathbb{T}",
              Th: "{\\bm{\\theta}}",
              Thh: "{\\bm{\\Theta}}",
              Tt: "\\mathcal{T}",
              Uu: "\\mathcal{U}",
              Vv: "\\mathcal{V}",
              W: "\\mathbb{W}",
              Ww: "\\mathcal{W}",
              X: "\\mathbb{X}",
              Xx: "\\mathcal{X}",
              Yy: "\\mathcal{Y}",
              Z: "\\mathbb{Z}",
              Zz: "\\mathcal{Z}",
              abs: ["\\left| #1 \\right|", 1],
              alf: "{\\alpha}",
              b: ["{\\bm{#1}}", 1],
              bm: ["\\boldsymbol{#1}", 1],
              br: ["\\left\\langle#1\\right\\rangle", 1],
              bt: "\\beta",
              co: ["\\overset{\\circ}{#1}", 1],
              d: "\\mathrm{d}",
              diag: ["\\operatorname{diag}\\left(#1\\right)", 1],
              dx: "\\,\\mathrm{d}x",
              dy: "\\,\\mathrm{d}y",
              eps: "\\varepsilon",
              et: "{\\bm{\\eta}}",
              ex: ["\\mathrm{exp}\\left(#1\\right)", 1],
              fk: ["\\mathfrak{#1}", 1],
              fracc: ["{#1}/{#2}", 2],
              frc: ["\\left(#2)^{-1}(#1\\right)", 2],
              iso: "\\xrightarrow{\\sim}",
              ker: "\\bm{ker}",
              mat: ["\\begin{bmatrix}{#1}\\end{bmatrix}", 1],
              mathbbm: ["\\mathbb{#1}", 1],
              mathds: ["\\mathbb{#1}", 1],
              norm: ["\\left\\lVert #1 \\right\\rVert", 1],
              om: "\\omega",
              postref: ["\\href{https://nowheredifferentiable.com/posts/#1/}{#3}", 3],
              proj: "\\mathrm{proj}",
              qb: ["\\left[#1\\right]", 1],
              qp: ["\\left(#1\\right)", 1],
              qt: ["\\left(#1\\right)", 1],
              red: ["{\\color{red}#1}", 1],
              rm: ["\\mathrm{#1}", 1],
              set: ["\\left\\{#1\\right\\}", 1],
              star: "*",
              tl: ["\\widetilde{#1}", 1],
              tll: ["\\widetilde{#1}", 1],
              vol: "\\mathrm{vol}",
              wh: ["\\widehat{#1}", 1],
              x: "\\bm{x}",
              xxi: "{\\bm{\\xi}}",
              y: "\\bm{y}"
            }
          }
        };
        </script>
---

##  Three line summary

## Why should I care?

## Notation

## Introduction

In previous posts we already used the Itô representation formula, which allows us to represent square integrable random variable $\xi$ of mean zero as an Itô integral of some stochastic process $X$. In general it is not possible to obtain an explicit expression for $X$, however in the case where $\xi$ is Malliavin differentiable we will obtain the expression $\E[D_t\xi |\Ff_t]$, that is,

::: {#thm-1 name="Clark-Ocone Formula"}

Given $\xi \in \mathbb{D}_{1,2}$ it holds that

$$
\xi =\E[\xi ]+\int_{I}\E[D_t\xi |\Ff_t] dW(t).
$$

:::

To prove the following theorem we first have to take a brief detour to obtain some properties of the conditional expectation of (iterated) Itô integrals. First we give the following definition

::: {#def-1}

Let $B\in \Bb(I)$, we define $\Ff_G$ to be the completion of the $\sigma$-algebra generated by the Itô integrals

$$
\left\{dW(A):=\int_{A}dW(t): A\subset B, A \in \Bb(I)\right\}.
$$

:::

In practice one often takes $B=[0,t]$ in which case one obtains that $\Ff_B$ is the completion of the $\sigma$-algebra generated by $\{W(s): s<t\}$. That is,  $\Ff_B=\Ff_t$. We need the following results to prove the Clark-Ocone formula. Firstly, we have that the conditional expectation of the Itô integral of a deterministic function $f$ is just the Itô integral of $f$ on the smaller set. That is,

::: {#lem-1}

Let $f\in L^2(I,\Bb(I))$ and $B\in \Bb(I)$, then it holds that

$$
\E\left[\int_{I}f(t)dW(t)|\Ff_B\right]=\int_{B} f(t) dW(t).
$$

:::

::: {.proof}

By definition of conditional expectation, we need to show that given a Borel set $A \subset B$ it holds that

$$
\E\left[dW(A)\int_{I}f(t)dW(t)\right]=\E\left[dW(A)\int_{B}f(t)dW(t)\right]
$$

This follows from the Itô-isometry as both are equal to $\int_{A}f(t) d t$.

:::

\begin{observation}
	As a technicality we note that to complete the proof it is necessary to show that the right hand side of the equality of the lemma is indeed $\Ff_B$ measurable. This can be shown by assuming $f\in C_c(I)$ and then approximating the integral in the usual way as  a simple sum, that is
	$$\int_{B} f(t) dW(t)\sim \sum_{n=0}^{N}f(t_n)dW([t_{n},t_{n+1})\cap B)$$.
	Which is $\Ff_B$ measurable.
\end{observation}
Using this lemma we can prove a more general result when we now integrate a stochastic process  $X$.

::: {#lem-cond-exp-process}

Let $X\in L^2(I\times\Omega,\Bb(I),\mathbb{F}_T)$ be a process adapted to $F_t$, then it holds that

$$
\E\left[\int_{I}X(t)dW(t)|\Ff_B\right]=\int_{B} \E[X(t)|\Ff_B] dW(t).
$$

:::

::: {.proof}

The proof is analogous to that of the previous lemma. Furthermore, the justification of the $\Ff_B$ measurability of the right hand side is also carried out in the same fashion as in Observation @obs.

:::

Using the above lemma    may now prove the following way of taking conditional expectations in the Chaos expansion

::: {#lem-2}

Let $\xi \in L^2(\Omega,\Ff)$ have the chaos expansion $f=\sum_{n=0}^{\infty} I_n(f_n)$ and consider $B\in \Bb(I)$. Then it holds that

$$
\E[I_n(f_n)|\Ff_B]=I_n(1_B^{\otimes n}f_n).
$$

Where $1_B^{\otimes n}(t_1,\ldots,t_n):=1_B(t_1),\cdot 1_B(t_n)$. As a result, we have that

$$
\E[\xi ]=\sum_{n=0}^{\infty}  f_n(x).
$$

:::

::: {.proof}

The proof proceeds by induction over $n$, the case $n=1$ holds by the previous Lemma @lem-cond-exp-process. Suppose by hypothesis of induction that it holds for $n$, then we have that for  $n+1$

$$
\begin{aligned}
& \E[I_{n+1}(f_{n+1})|\Ff_B]                                                                                                   \\
	 & =\int_{B}\E\left[\int_{0}^{t_{n+1}}\cdot \int_{0}^{t_1} f_{n+1}(t_1,\ldots,t_{n+1})dW(t_1)\cdot  dW(t_n)\mid\Ff_G\right]dW(t_{n+1}) \\
	 & =\int_{B} I_n(1_B^{\otimes n}(\cdot )f_n(\cdot ,t_{n+1}))dW(t_{n+1})=I_n(1_B^{\otimes (n+1)}f_{n+1}).
\end{aligned}
$$

Where the first equality is due to Lemma @lem-cond-exp-process and the second equality is a consequence of the hypothesis of induction. Finally the last past of the theorem follows by taking limits, as we recall that the chaos expansion converges in $L^2(\Omega)$ and thus also in $L^1(\Omega)$.

:::

Clark-Ocone's formula is now a straightforward calculation using the previous.

::: {.proof}

Proof of Theorem 1: By, definition of the Malliavin derivative and the just proved Lemma it holds that
	
$$
\begin{aligned}
\int_{I}\E[D_tF|\Ff_t] dW(t) & =\sum_{n=1}^{\infty} n\int_{I} I_{n-1}(1_{[0,t]}^{\otimes(n-1)}f_{n-1}(\cdot ,t))dW(t)=\sum_{n=1}^{\infty} I_n(f_n) \\
		                             & =\xi -I_0(\xi )=\xi -\E[\xi ].
\end{aligned}
$$

:::

## White noise analysis

We recall that the space of tempered distributions $\Ss(\R^d\to \Cc^m)$ is the space of infinitely differentiable distributions that decrease faster than the inverse of any polynomial. That is,

$$
\mathcal{S}(\R^d\to\C^m):=\lbrace f\in\C^\infty(\R^d\to\C^m):x^\alpha D^\beta f\in L^\infty(\R^d\to\C^m)\quad\forall\hspace{2pt}\alpha,\beta\in \Z^d\rbrace.
$$

Furthermore, given a  vector space $V$ together with a countable family of semi-norms $\lbrace p_j\rbrace_{j=0}^\infty$ with the property that: given $x\neq 0$, there exists $j$ such that $p_j(x)\neq 0$. Then

$$
d(x,y):=\sum_{j=0}^\infty 2^{-j}\frac{p_j(x-y)}{1+p_j(x-y)}\quad\forall{x,y}\in{X}
$$ {#eq-seminormsgivemetric}

is a translation invariant metric on $V$. We shall denote the dual of $V$  by \[V':=\lbrace w:V\to\C\hspace{2pt}: w \hspace{2pt}\text{continuous}\rbrace.\]
Due to the metric we set on $V$ one can verify that $w\in V'$ iff there exist $C\in\R,N\in\N$ such that

$$
\abs{w(u)}\leq C\sum_{j=1}^N p_j(u)\quad\forall{u}\in{V}
$$ {#eq-linearityfrechspace}

In the case of the Schwartz space $\Ss(\R^d\to\C^m)$ we give it the topology induced by

$$
p_k(u):=\sum_{\abs{\alpha}\leq k} \sup_{x\in\R^d}\abs{x}^k \abs{D^\alpha u(x)}.
$$ {#eq-seminornormsschwartz}

Though, as is generally the case with Fréchet spaces, other families of semi-norms the reader may be familiar with such as
\[p_{k,\alpha}:=\sup_{x\in\R^d}\abs{x}^k \abs{D^\alpha u(x)};\quad\text{or}\quad p'_{k,\alpha}:=\sup_{x\in\R^d}(1+\abs{x})^k \abs{D^\alpha u(x)}\]
induce equivalent topologies. We note that with this metric $\Ss(\R^d\to\C^m)$ is a Fréchet space (that is a complete Hausdorff topological vector space). For a quick proof (in the case $m=1$) based on the fundamental theorem of calculus see for example [@Foll] page 237.
\bigbreak With this we move on to discuss space of tempered distributions.\\
\\
For our purposes it will suffice to consider the one-dimensional real case $\Ss(\R):=SS(\R\to\R)$. An equivalent way to generate the topology given by @eq-seminormsgivemetric-@eq-seminornormsschwartz on $\Ss(\R)$ is to consider a sequence of decreasing  subspaces of $L^2(\R)$

$$
L^2(\R):=\Ss_0(\R)\supset \Ss_1(\R)\cdots\supset \Ss_p(\R)\cdots.
$$

Together with their norms $\norm{\cdot }_p$. Where these spaces and norms are taken such that

$$
\Ss(\R)=\bigcap_{n \in \N}\Ss_p(\R),
$$

, the topology generated by $\norm{\cdot }_p$ coincides with the previously defined one which was generated by $|\cdot |_p$, and the inclusion $\Ss_{p+1}(\R)\hookrightarrow \Ss_p(\R)$ is Hilbert Schmidt. This construction is very technical and can be found detailed in [@becnel2004schwartz]. The usage of this construction is that it forms part of a more general framework, which is as follows.

::: {#def-2}

We say that a real Hilbert space $\Nn$ is a nuclear space if there exist a decreasing family of subspaces $(H_p,\norm{\cdot }_p)$ such that

$$
\Nn(\R)=\bigcap_{n \in \N}H_p(\R).
$$

Where the topology on $\Nn$ is generated by the family $\norm{\cdot }_p$, $\Nn$ is dense in $\Ss_p(\R)$,and for each $p \in \Nn$ there exists $q>p$ such that the inclusion  $H_q\hookrightarrow H_p$ is Hilbert Schmidt.

:::

By the previous discussion $\Ss(\R^d)$ is a nuclear space. Furthermore, we have the following,

::: {#thm-2 name="Bochner-Milos theorem"}

Let $\Nn$ be a nuclear space, then given a function $r:\Ss(\R)\to\C$ that is continuous and positive definite there exists a unique finite measure $\mu$ on $\Bb(\Nn)$ such that

$$
r(\phi)= \int_{\Nn} e^{i\br{\omega,\phi}}d \mu(\omega),\quad\forall \phi\in \Nn.
$$

:::

We note that if $r(0)=1$ then  $\mu$ is a probability measure. When $r(\phi):=e^{-\frac{1}{2}\norm{\phi}_{H_0}^2}$ we call the probability space $(\Nn',\Bb(\Nn),\mu )$ the *Gaussian space associated to $\Nn'$*. Particularizing this to $\Nn=\Ss(\R)$ we obtain the following classical space

::: {#def-3}

The *white noise probability space* is the Gaussian space $(\Ss'(\R),\Bb(\Ss'(\R)),\mathbb{P} )$ associated to $\Ss'(\R)$. That is, $\mathbb{P}$ is a probability measure on $\Ss'(\R)$ such that

$$
\int_{\Ss(\R)} e^{i\br{\omega,\phi}}d \mathbb{P}(\omega)=e^{-\frac{1}{2}\norm{\phi}_{L^2(\R)}^2},\quad\forall \phi\in \S(\R).
$$

:::

For a simpler and quick construction of this space without the explicit usage of the most general form of the Bochner-Milos theorem see also [@holden1996stochastic] appendix A.
We now make the following definition,

::: {#def-4}

*Smoothed* white noise is the mapping $w:\Ss(\R)\times\Ss'(\R)\to \R$ defined by $\dot{W}(\phi,\omega):=\br{\omega,\phi}$.

:::

We note that, since $w$ is continuous it is measurable. Furthermore, if for each $\phi\in \Ss(\R)$ we consider the random variable   $\dot{W}(\phi):=\dot{W}(\phi,\cdot )$ on the white noise probability space $(\Ss'(\R),\Bb(\Ss'(\R)),\mathbb{P} )$ then, by basic theory of real valued Gaussian variables and @eq-characteristic-func, $\dot{W}_\phi$ is a centered Gaussian variable with variance $\norm{\phi}_{L^2(\R)}$. In consequence we have an isometry

$$
\begin{aligned}
(\Ss(\R),\norm{\cdot }  _{L^2(\R)} & )\to L^2(\Ss(\R),d\mathbb{P}) \\
	                                   & \phi\to \dot{W}_\phi.
\end{aligned}
$$

By density of $\Ss(\R)$ in $L^2(\R)$ the above isometry allows us to extend the definition of $\dot{W}(f)$ to all $f\in L^2(\R).$ Since the above mapping is an isometry is also conserves the inner product and we get the defining equality of white nois

$$
\E[\dot{W}(f)\dot{W}(g)]=\br{f,g}_{L^2(\R)},\quad\forall f,g\in L^2(\R).
$$

This shows that $\dot{W}$ is in fact a white noise on $L^2(\R)$. Another point of interest is that, if we write

$$
\int_{\R}f(t) dW(t):=\dot{W}(f),\quad\forall f\in L^2(\R).
$$ {#eq-iso}

Then

$$
W(t):=\int_{0}^t dW(t):= \int_{\R}1_{[0,t]} dW(t),
$$

is in fact a Wiener process. The fact that $W(0)=0$ follows readily from the definition. Further,  $W(t)$ is a Gaussian random variable as it is defined as the limit in $L^2(\R)$ (and thus in distribution) of a sequence of Gaussian random variables $\dot{W}(\phi_n)$ where $\phi_n$ are Schwartz functions converging to $f$. The independence of $W(t)$ and  $W(s)$ is immediate by the isometry in @eq-iso. Finally, since $\dot{W}$ is a linear isometry, for any given $t\geq s$

$$
\E[|W(t)-W(s)|^2]=\E[|\dot{W}(1_{[s,t]})|^2]=\norm{1_{[0,t-s]}}_{L^2(\R)}^2=t-s.
$$

So by Kolmogorov's lemma, we make take a modification of $\dot{W}$  that  is $\gamma$ Hölder continuous for all $\gamma<\frac{1}{2}$. This concludes that indeed $W(t)$ is a Wiener process.\\\\
For completeness we note that the above construction may be replicated exactly to obtain a white noise on $L^2(\R^d)$. In this case the field on $\R^d$ defined by $W(x):=\dot{W}(1_{[0,x]})$ is called the Gaussian sheet.

## References

::: {#refs}
:::
